### ISSUE TITLE
ssl errror 

### ISSUE THREAD

**Issue by maitrey** [pycontribs/jenkinsapi#197]
I get SSL exception error when trying to use jenkinsapi-0.2.16.
Any queries, for example listing jobs, listing build artifacts cannot be performed.
import jenkinsapi
from jenkinsapi.jenkins import Jenkins
J=Jenkins('https://localhost:8181', username, pwd)

gives, SSLError: [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

Has anyone come across this error?
Is there a workaround?
Jenkins version : 1.509.2

**Comment by Ohadbasan** [comment]
This solution did not work for me.
but it's close
what I did is the following


class SSLRequester(Requester):
    def __init__(self, username=None, password=None):
        super(SSLRequester, self).__init__(username, password)

    def get_request_dict(self, params=None, data=None, files=None, headers=None, **kwargs):
            requestKWargs = super(SSLRequester, self).get_request_dict(params=params, headers=headers, allow_redirects=kwargs['allow_redirects'])
            requestKWargs['verify'] = False
            return requestKWargs

and when you initialize the request object you have to provide the password


J = Jenkins('https://jenkins.interjunk.com',user,pass, requester=SSLRequester(user, pass))
