### ISSUE TITLE
Module Import Error - No module named jenkins

### ISSUE THREAD

**Issue by thorrsson** [pycontribs/jenkinsapi#253]
Fresh virtualenv (tried with --no-site-packages and without)
   

     (jenkins) ⮀ timhunter ⮀ ~/virtualenvs ⮀ ls jenkins/lib/python2.7/site-packages/jenkinsapi
    __init__.py               config.py                 executors.pyc             job.py                    nodes.pyc                 result_set.py
    __init__.pyc              config.pyc                fingerprint.py            job.pyc                   plugin.py                 result_set.pyc
    api.py                    constants.py              fingerprint.pyc           jobs.py                   plugin.pyc                utils
    api.pyc                   constants.pyc             invocation.py             jobs.pyc                  plugins.py                view.py
    artifact.py               custom_exceptions.py      invocation.pyc            mutable_jenkins_thing.py  plugins.pyc               view.pyc
    artifact.pyc              custom_exceptions.pyc     jenkins.py                mutable_jenkins_thing.pyc queue.py                  views.py
    build.py                  executor.py               jenkins.pyc               node.py                   queue.pyc                 views.pyc
    build.pyc                 executor.pyc              jenkinsbase.py            node.pyc                  result.py
    command_line              executors.py              jenkinsbase.pyc           nodes.py                  result.pyc
     (jenkins) ⮀ timhunter ⮀ ~/virtualenvs ⮀ jenkins/bin/python2.7
    Python 2.7.2 (default, Oct 11 2012, 20:14:37)
    [GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import jenkinsapi
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "jenkinsapi.py", line 3, in <module>
        from jenkinsapi.jenkins import Jenkins
    ImportError: No module named jenkins
    >>> from jenkinsapi.jenkins import Jenkins
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "jenkinsapi.py", line 3, in <module>
        from jenkinsapi.jenkins import Jenkins
    ImportError: No module named jenkins

Any Suggestions would be greatly appreciated

**Comment by Tset-Noitamotua** [comment]
Same issue on a Windows 7 machine

```shell
(JENKINSAPI) C:\temp
$ python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from jenkinsapi.jenkins import Jenkins
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jenkinsapi.py", line 1, in <module>
    from jenkinsapi.jenkins import Jenkins
ImportError: No module named jenkins
>>> import jenkinsapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jenkinsapi.py", line 1, in <module>
    from jenkinsapi.jenkins import Jenkins
ImportError: No module named jenkins
>>> import sys
>>> from pprint import pprint
>>> pprint(sys.path)
['',
 'C:\\Windows\\system32\\python27.zip',
 'C:\\Users\\me\\Envs\\JENKINSAPI\\DLLs',
 'C:\\Users\\me\\Envs\\JENKINSAPI\\lib',
 'C:\\Users\\me\\Envs\\JENKINSAPI\\lib\\plat-win',
 'C:\\Users\\me\\Envs\\JENKINSAPI\\lib\\lib-tk',
 'C:\\Users\\me\\Envs\\JENKINSAPI\\Scripts',
 'c:\\python27\\Lib',
 'c:\\python27\\DLLs',
 'c:\\python27\\Lib\\lib-tk',
 'C:\\Users\\me\\Envs\\JENKINSAPI',
 'C:\\Users\\me\\Envs\\JENKINSAPI\\lib\\site-packages']
>>>
```

I´m very sure that it worked initially, but for some reason it does not work any more even if I create a fresh Virtualenv (bwt: I use '[virtualenvwrapper-win](https://github.com/davidmarble/virtualenvwrapper-win)' to manage my virtual envs)
