### ISSUE TITLE
How to access jobs under folders in jenkins

### ISSUE THREAD

**Issue by thexder1** [pycontribs/jenkinsapi#281]
I have been looking at this api for a while now and as far as I can tell the folders are seen as jobs and there are no keys under them. Looking at all jobs shows the jobs at the root of the hierarchy and the folder that I have there, but nothing below that. There does not appear to be any parameters or configuration or anything else that the api can get. Is there any way to get this API to read the jobs that are under folders in Jenkins?

**Comment by ChaiBapchya** [comment]
Any work done on it yet?

**Comment by Jess713** [comment]
any work done on it?
