### ISSUE TITLE
Get all the revision numbers from a build or job

### ISSUE THREAD

**Issue by kerbam** [pycontribs/jenkinsapi#317]
Any way to grab all the revision numbers for a build? It appears that the only revision that is returned is the last revision number. There are times within builds where multiple revisions are built and it would be nice to have all those revision numbers instead of just the latest one.

**Comment by lechat** [comment]
It looks like there are two places to get this information from:
- from changeSet.revisions, this is where jenkinsapi gets revisions from
- from changeset.items, this is what you want

I've added Build.get_changeset_items() which will return ``items`` list from "changeSet" - this will allow you to calculate what you need w/p touching Build._data
