### ISSUE TITLE
Forwarding address of Queue item returned from jenkins is not FQDN address.

### ISSUE THREAD

**Issue by rustyscottweber** [pycontribs/jenkinsapi#328]
in job.py of the unstable branch.
<pre>
<code>
redirect_url = response.headers['location']
if not redirect_url.startswith("%s/queue/item" % self.jenkins.baseurl):
            if files:
                raise ValueError('Builds with file parameters are not '
                                 'supported by this jenkinsapi version. '
                                 'Please use previous version.')
            else:
                raise ValueError("Not a Queue URL: %s" % redirect_url)
</code>
</pre>
if a FQDN address was used to instantiate the jenkins object, these urls will not match because the redirect url returned by the response header to the invocation is not the FQDN of the server.
Example.
redirect_url = http://ems-qa/queue/item/26
jenkins.baseurl = http://ems-qa.this.is.an.example.org

**Comment by spikergit1** [comment]
:+1:

**Comment by kaos** [comment]
:+1: 

I got this simply because I called jenkins over `https` and got a redirect to a mere `http` version. Bah.

**Comment by rustyscottweber** [comment]
I forgot to post a quasi resolution to this..
https://issues.jenkins-ci.org/browse/JENKINS-26150
It would appear that there is a way to configure the baseurl in jenkins.  However,it still seems like there is a problem because as Kaos mentioned, he was accessing the server through https and was redirected to the http address which caused the same problem.  It sounds like the core should have a better method for coming up with the forwarding address but that's just my opinion.  It shouldn't be terribly difficult to generate the url based off of the origional url that was made to query the jenkins server. Example: http://stackoverflow.com/questions/5450066/how-to-get-the-original-request-url-from-a-servlet-jsp-after-multiple-servlet-fo
