### ISSUE TITLE
Error on invoking job (gaierror(11004, 'getaddrinfo failed)

### ISSUE THREAD

**Issue by rustyscottweber** [pycontribs/jenkinsapi#334]
On the latest experimental branch of the jenkinsapi, the following error was returned while attempting to invoke a job.   The error is thrown intermittently as new jobs are created.  Maybe 1/3 jobs will fail with this error which is a problem for . As far as I can tell, the job was successfully started, however the jenkinsapi for python completely crashed with the following stack trace.
<code><pre>
Launching ION_Update on emsqa-proxy0 with the following build params: {'ION_RELEASE': 'coffee', 'NODE_NAME': 'emsqa-proxy0', 'ION_BUILD': 'LATEST', 'RUN_LABEL': 'emsqa-proxy0', 'APPLIANCES': 'ion-qa-cluster', 'NODE_LABELS': 'emsqa-proxy0'}
19:33:46 Traceback (most recent call last):
19:33:46   File "C:\Users\ADMINI~1\AppData\Local\Temp\hudson5699247368797024137.py", line 
22, in <module>
19:33:46     queueitem = jj.invoke(block=True, build_params=build_params)
19:33:46   File "build\bdist.win-amd64\egg\jenkinsapi\job.py", line 222, in invoke
19:33:46   File "build\bdist.win-amd64\egg\jenkinsapi\queue.py", line 132, in block_until_complete
19:33:46     remaining = endtime - _time()
19:33:46   File "build\bdist.win-amd64\egg\jenkinsapi\queue.py", line 138, in block_until_building
19:33:46     self.not_empty.notify()
19:33:46   File "build\bdist.win-amd64\egg\jenkinsapi\jenkinsbase.py", line 57, in poll
19:33:46   File "build\bdist.win-amd64\egg\jenkinsapi\jenkinsbase.py", line 67, in _poll
19:33:46   File "build\bdist.win-amd64\egg\jenkinsapi\jenkinsbase.py", line 77, in get_data
19:33:46   File "build\bdist.win-amd64\egg\jenkinsapi\utils\requester.py", line 95, in get_url
19:33:46   File "C:\Python27\lib\site-packages\requests\api.py", line 65, in get
19:33:46     return request('get', url, **kwargs)
19:33:46   File "C:\Python27\lib\site-packages\requests\api.py", line 49, in request
19:33:46     response = session.request(method=method, url=url, **kwargs)
19:33:46   File "C:\Python27\lib\site-packages\requests\sessions.py", line 461, in request
19:33:46     resp = self.send(prep, **send_kwargs)
19:33:46   File "C:\Python27\lib\site-packages\requests\sessions.py", line 573, in send
19:33:46     r = adapter.send(request, **kwargs)
19:33:46   File "C:\Python27\lib\site-packages\requests\adapters.py", line 415, in send
19:33:46     raise ConnectionError(err, request=request)
19:33:46 requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(11004, 'getaddrinfo failed
</pre></code>

As far as I can tell, jenkinsapi was attempting to retrieve an address that didn't exist.  However since this is such an intermittent issue, I can't quite figure out on which URL the error is occurring.   Sooo... Valid debugging tips are encouraged to help find the root of the issue.

My current running theory is that either the queitem page is not existant because it either hasn't been created yet or has been garbage collected in which case error handling code might need to be added.

**Comment by lechat** [comment]
You can get url if you put ``print url`` in ``jenkinsbase`` before line 77.

https://github.com/salimfadhley/jenkinsapi/blob/master/jenkinsapi/jenkinsbase.py#L77

``getaddinfo`` error is WSANO_DATA:
> Valid name, no data record of requested type.
>
>    The requested name is valid and was found in the database, but it does not have the correct associated data being resolved for. The usual example for this is a host name-to-address translation attempt (using gethostbyname or WSAAsyncGetHostByName) which uses the DNS (Domain Name Server). An MX record is returned but no A record—indicating the host itself exists, but is not directly reachable.
http://msdn.microsoft.com/en-us/library/windows/desktop/ms740668%28v=vs.85%29.aspx

It looks like this error is not jenkinsapi related, but caused by your infrastructure. Anyway, knowing the url would be helpful.

**Comment by rustyscottweber** [comment]
The URL culprit seems to be:
http://jenkins-qa/job/Update_Job/249/api/python
With the parameters being:
{'depth': 1, 'tree': 'building'}

Querying the item through the url with curl returns
<code><pre>curl -H "depth: 1" -H "tree: building" http://jenkins-qa/job/Update_Job/249/api/python
{"actions":[{"parameters":[{"name":"APPLIANCES","value":"ion-qa-cluster"},{"name":"APPLIANCE_PASSWORDS"},{"name":"RELEASE","value":"XXX"},{"name":"BUILD","value":"XXX"},{"name":"RUN_LABEL"}]},{"causes":[{"shortDescription":"Started by user jenkins","userId":"jenkins","userName":"jenkins"}]},{},{},{},{},{}],"artifacts":[],"building":False,"description":None,"duration":2036268,"estimatedDuration":681237,"executor":None,"fullDisplayName":"Update_Job
#249","id":"2015-01-19_15-58-45","keepLog":False,"number":249,"result":"SUCCESS","timestamp":1421708325146,"url":"http://jenkins-qa/job/IUpdate_Job/249/","builtOn":"emsqa-proxy0","changeSet":{"items":[],"kind":"hg"},"culprits":[]}
</pre></code>

Is it possible that there is a failure after the job is no longer in the queue, when jenkins has started to build it, this page simply doesn't exist yet?

I'll add some try except handling code around the url request to test the theory.  In the case that the exact same request succeeds a mere fraction of a second later, this is a race condition of the page in question existing.  However, if the page continues to not be requested, the error should propagate back upward..

**Comment by rustyscottweber** [comment]
I got to the bottom of this today.  Somehow, very rarely, the DNS fails to respond to a name lookup request.  I still have to figure out why, but in the meantime, do we think that it would be beneficial to include an inherent retry into the jenkinsbase class?
According to the following line, it looks like that was something that had already been planned but not completly fleshed out.  Else, why would there be a RETRY_ATTEMPTS variable?
https://github.com/salimfadhley/jenkinsapi/blob/master/jenkinsapi/jenkinsbase.py#L17 

Would something like the following even be appropriate?
<code>
<pre>class JenkinsBase(object):

    """
    This appears to be the base object that all other jenkins objects are inherited from
    """
    RETRY_ATTEMPTS = 10
    FAILURE_SLEEP = 0.1
    def get_data(self, url, params=None, tree=None):
        requester = self.get_jenkins_obj().requester
        if tree:
            if not params:
                params = {'tree': tree}
            else:
                params.update({'tree': tree})

        attempts = 0
        max_attampts = JenkinsBase.RETRY_ATTEMPTS
        sleep_interval = JenkinsBase.FAILURE_SLEEP
        while True:
            try:
                response = requester.get_url(url, params)
                break
            except:
                # todo logme "attempt:%s\nurl:'%s'\nparams:'%s'" % (attempts, url, params)
                if attempts > max_attampts:
                    raise
                else:
                    attempts += 1
                    time.sleep(sleep_interval)
        if response.status_code != 200:
            logging.error('Failed request at %s with params: %s %s',
                          url, params, tree if tree else '')
            response.raise_for_status()
        try:
            return ast.literal_eval(response.text)
        except Exception:
            logging.exception('Inappropriate content found at %s', url)
            raise JenkinsAPIException('Cannot parse %s' % response.content)
</pre>
</code>
