### ISSUE TITLE
Que item does not exist if waiting for a period of time before waiting for build to finish.

### ISSUE THREAD

**Issue by rustyscottweber** [pycontribs/jenkinsapi#335]
While running the following code.

<pre><code>
jenkinsjobs = get_all_jenkins_jobs()
queueitems = []
for jj in jenkinsjobs:
    queueitem = jj.invoke(block=False, build_params=build_params)
    queueitems.append(queueitem)
for queueitem in queueitems:
    queueitem.block_until_complete(30)
    status = queueitem.get_build().get_status()
    LOGGER.info("%s build %s = %s" % (queueitem.get_job_name(), queueitem.get_build_number(), status))
</code></pre>
I noticed that an exception gets repeated multiple times and the pythonic queue object will never return the state of the build.
<pre>
11:29:16 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:29:46 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:30:16 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:30:47 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:31:17 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:31:47 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:32:18 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:32:48 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:33:18 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:33:49 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:34:19 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:34:49 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:35:20 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:35:50 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:36:20 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:36:51 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:37:21 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:37:51 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:38:22 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:38:52 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:39:23 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:39:53 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
11:40:23 ERROR:root:Failed request at http://jenkins/queue/item/4128/api/python with params: None 
</pre>

This is because the queue item no longer exists on the jenkins server.  After watching the bug in process, I can see that the job was kicked off and that the queue item did exist at one time.  However, it appears that queue items are ephemeral/temporary and cannot be depended on to exist for any amount of time after the queue item has been canceled or the build has finished.

**Comment by rustyscottweber** [comment]
If queue items are thread safe, I wonder if it would make sense to have each queue item keep track of their own thread which is following the build process from beginning to end.

**Comment by FMCorz** [comment]
I'm experiencing the same issue. Is there a workaround?

**Comment by lechat** [comment]
I think that this is a bug in Jenkins itself. We used new Jenkins API for invoking builds, which is working faster, but some edge cases are not working.

@salimfadhley could you take a look?

**Comment by talcloudshare** [comment]
I'm also experiencing this issue

**Comment by rustyscottweber** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-31039

**Comment by tuwid** [comment]
Any luck with this ?

**Comment by rustyscottweber** [comment]
If I recall correctly, the core issue was fixed. However the job is only guaranteed to be in the queue for some number o if seconds, 30 I believe. In other words, you can't kick a job, sleep for 5 minutes while another job is running then check the queue. The solution I came up with is that each job should be spun into it's own thread which checks the job every second or so l. But that code is long since dead since they added pipelines to mainstream jenkins.

**Comment by tuwid** [comment]
> If I recall correctly, the core issue was fixed. However the job is only guaranteed to be in the queue for some number o if seconds, 30 I believe. In other words, you can't kick a job, sleep for 5 minutes while another job is running then check the queue. The solution I came up with is that each job should be spun into it's own thread which checks the job every second or so l. But that code is long since dead since they added pipelines to mainstream jenkins.

Changed the implementation to something like this and so far its working well. 
This is part of the JenkinsManager object that takes care of the jobs
```
    def wait_for_completion(self, domain_name: Optional[str] = None):
        """ Wait for all jobs to complete for the given domain."""
        queue_items_for_domain = self.domain_jobs.get(domain_name, [])
        logger.info(
            "[jenkins_manager]Waiting for %s jobs to complete for %s",
            len(queue_items_for_domain),
            domain_name
        )

        for queue_item in queue_items_for_domain:
            self._wait_for_queue_item_completion(queue_item, domain_name)

        self.domain_jobs[domain_name] = []
        logger.info("[jenkins_manager]Jenkins jobs for domain %s completed.", domain_name)

    def _wait_for_queue_item_completion(self, queue_item, domain_name):
        """ Helper method to wait for a specific queue item to complete """
        attempts = 0
        while attempts < RETRY_COUNT:
            try:
                queue_item.block_until_complete()
                build = queue_item.get_build()
                if build.is_good():
                    self.domain_jobs[domain_name].remove(queue_item)
                    logger.info(
                        "[jenkins_manager]Done with build #%s with params: %s",
                        build.get_number(), build.get_params()
                    )
                else:
                    logger.error(
                        "[jenkins_manager]Build #%s failed with params: %s",
                        build.get_number(), build.get_params()
                    )
                break
            except RequestException as e:
                attempts += 1
                logger.error(
                    "[jenkins_manager]Error in Jenkins API call, attempt %d of %d: %s",
                    attempts, RETRY_COUNT, str(e)
                )
                sleep(RETRY_DELAY)
            except Exception as e:
                logger.error(
                    "[jenkins_manager]Unexpected error: %s", str(e)
                )
                break

        if attempts == RETRY_COUNT:
            logger.error(
                "[jenkins_manager]Reached max retries for queue item. "
                "Please manually verify the status of the job."
            )

```
