### ISSUE TITLE
invoke() with build cause

### ISSUE THREAD

**Issue by vitsfr** [pycontribs/jenkinsapi#359]
I don't know if it's a bug/untested feature or if I just do it the wrong way. I want to invoke a build with a build cause (actually to solve the problem described in https://github.com/salimfadhley/jenkinsapi/issues/335), but I can't make it work.
I tried putting in a string, a dictionary, a list of dictionaries using the fields I get when I look at what the API returns for jobs wit set build cause, but none of it shows up anywhere in the triggered build.

Can it be done? How's it done?

**Comment by InbarRose** [comment]
I am having the same problem. I opened an issue on StackOverflow.
http://stackoverflow.com/q/37391575/1561176

**Comment by lechat** [comment]
How would you set build cause in Jenkins UI? I never used that feature, so help me to find it.
