### ISSUE TITLE
Can't use both file and string parameters

### ISSUE THREAD

**Issue by sweetsoftware** [pycontribs/jenkinsapi#363]
When invoking a build that takes both file and string parameters, this error is raised:

`ValueError: Builds with file parameters are not supported by this jenkinsapi version. Please use previous version.`

When using only strings and only the file it works fine. Also, when commenting the code raising this exception, the build is triggered and works fine, but the python function never returns.

Are there any reasons why this combination of parameters have been deactivated ?

**Comment by lechat** [comment]
This was deactivated because Jenkins doesn't support this though QueueItem API. At the same time the use of QueueItem API is encouraged by Jenkins developers because it provides ability to find exact build that was triggered by particular job invocation.
I hope that if somebody raises that in Jenkins issue log, the issue will be fixed.

**Comment by sweetsoftware** [comment]
The error is on Jenkins' side, however it seems to work quite well for me when guessing the next QueueItem with get_next_build_number().

The down side is that if a build gets triggered between our build and the guess, we will wait for this build...except if we check the parameters to see if they match.

I submitted this PR (https://github.com/salimfadhley/jenkinsapi/pull/364) to allow querying Jenkins with this method.

Is it acceptable to do like this or should the API be enforced ?

**Comment by lechat** [comment]
As you can see pull request failed in the method that you have changed, so I can't accept that pull request. 

And yes, you are correct about the downside - it could lead to inconsistent result.
