### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by salimfadhley** [pycontribs/jenkinsapi#388]
Please let me know when ready.

**Comment by lechat** [comment]
I noticed that I haven't pushed my credentials work. I thought that I've done it. 

Will take a look at it this week.

**Comment by salimfadhley** [comment]
Okay, standing by

**Comment by lechat** [comment]
All done, just added some examples too.

I removed link to a badge from crate.io - it is no longer shown and makes pypi landing page look a bit abandoned.

I also removed a note in readme saying that library is incompatible with latest Jenkins versions.

**Comment by lechat** [comment]
Also, link to requires.io says that our dependencies are outdated even if we specifically saying that we depend on specific versions of libs that we use for unittesting only. Not sure if requires.io allows configuring this or not.

**Comment by salimfadhley** [comment]
I saw this - I made a release last weekend. 

What bug forces us to use old versions of those test-time libraries?

@lechat can you vote on whether you are happy for me to move the project into a "team" owned repository and out of my personal name-space.

**Comment by lechat** [comment]
If that improves Github search results, sure. 

I think that making fork of your personal repo to a team repo was not good idea because that would still link to your personal repo. I think that it is better to create repo and push all from your local. Just a minor observation, though.

**Comment by ssbarnea** [comment]
@salimfadhley and @lechat how about moving this project under [pycontribs organization](https://github.com/pycontribs) as there are more of us there that do maintain python packages, notable mentions would be JIRA and Confluence ones. 

It is much safer to keep these open-source projects under an organisation.

**Comment by lechat** [comment]
I don't mind. Not sure what good jira and confluence would bring, though. 

@salimfadhley tried to move this into jenkinsapi org, but it wasn't very successful.

**Comment by ssbarnea** [comment]
I added both of you as owners on PyContribs. This allows you to use the Transfer option to move the repository completely. That's preferred as it does keep the issues, PRs, ... forking doesn't.

**Comment by salimfadhley** [comment]
@ssbarnea I'd be happy to move it under pycontribs. I hardly ever do any work on this project these days, @lechat does 99% of everything so I'd give him the final vote. I don't think the Jenkins team were all that keen to endorse something that worked of their REST API which they consider to be non-stable.

**Comment by lechat** [comment]
I can't transfer this repository because I am not owner. @salimfadhley shall do it.

But before he does, I have couple of questions:
1. Who and how will do releases to pypi?
2. How is PyContribs managed? 

Perhaps it would be worth asking @ramonvanalteren to make his original repo private before we do transfer. The reason is that his original repo always comes first in Github search. It would be good is this repo will be first as repos are diverged significantly.

**Comment by ssbarnea** [comment]
I sent an invitation to join PyContribs to @salimfadhley 

Releasing is done on PYPI which luckily allows multiple people to do releases of the same package. Let's be sure that we have at least 2 people that can make a new release, preferably 3. 

My PYPI username is "sorin".
