### ISSUE TITLE
UnicodeDecodeError while using get_console()

### ISSUE THREAD

**Issue by kevinaloys** [pycontribs/jenkinsapi#396]
Jenkinsapi throws the UnicodeDecodeError while using the get_console() function to get the log for a jenkins job. Is there a fix? Thanks.

**Comment by lechat** [comment]
Could you please post here a stacktrace? Thanks!

**Comment by kevinaloys** [comment]
Hey hope this helped. Thanks
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-6-db61b1505d37> in <module>()
----> 1 meta.get_console()

/Users/kevin/anaconda/envs/jenkins/lib/python3.4/site-packages/jenkinsapi/build.py in get_console(self)
    398             return content
    399         elif isinstance(content, bytes):
--> 400             return content.decode('utf-8')
    401         else:
    402             raise JenkinsAPIException('Unknown content type for console')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 1983769: invalid continuation byte

**Comment by lechat** [comment]
Which version of Python?

**Comment by kevinaloys** [comment]
It's running Python 3.4.3
