### ISSUE TITLE
KeyError: 'computer' while attempting to iterate through nodes.

### ISSUE THREAD

**Issue by rustyscottweber** [pycontribs/jenkinsapi#397]
```python
jen = jenkinsapi.jenkins.Jenkins(os.getenv('JENKINS_URL'), USERNAME, PASSWORD)
nodes = jen.get_nodes()
nodes.keys()
Traceback (most recent call last):
  File "C:\Program Files\eclipse\plugins\org.python.pydev_4.3.0.201508182223\pysrc\pydevd_comm.py", line 1069, in doIt
    result = pydevd_vars.evaluateExpression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\Program Files\eclipse\plugins\org.python.pydev_4.3.0.201508182223\pysrc\pydevd_vars.py", line 344, in evaluateExpression
    result = eval(compiled, updated_globals, frame.f_locals)
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\jenkinsapi\nodes.py", line 40, in keys
    return list(self.iterkeys())
  File "C:\Python27\lib\site-packages\jenkinsapi\nodes.py", line 36, in iterkeys
    for item in self._data['computer']:
KeyError: 'computer'
```

**Comment by rustyscottweber** [comment]
Jenkins ver. 1.565.3
The data looks congruent to the data that is returned by jenkins.  With the same credentials, I can log in and make all the changes I desire manually.  However, it appears that the data returned does indeed not have a computer field.  Is there a reason that the api wouldn't return that data?  If so, it might be a good idea to at the very least add an error message better describing the problem.

**Comment by lechat** [comment]
Do you have "computer" in json when you access this url?

 $JENKINS_URL/computer/api/json?pretty=true

**Comment by rustyscottweber** [comment]
It does.
<pre><code>
{
  "busyExecutors" : 0,
  "computer" : [
    {
      "actions" : [
        
      ],
      "displayName" : "master",
      "executors" : [
        {
          
        },
        {
          
        },
        {
</code>
</pre>

**Comment by lechat** [comment]
Can't reproduce that. If you still experience this, please create new issue.
