### ISSUE TITLE
Moving the project to a team owned space

### ISSUE THREAD

**Issue by salimfadhley** [pycontribs/jenkinsapi#401]
Currently the project is in the "salimfadhley" namespace. 

I propose that we migrate over to a team-owned project space:
https://github.com/jenkinsapi/jenkinsapi

That way my fork becomes just another fork

**Comment by ripcurld00d** [comment]
:+1:

**Comment by rocktavious** [comment]
+1

**Comment by lechat** [comment]
Moved to `pycontribs`
