### ISSUE TITLE
Unnecessary loading of jobs?

### ISSUE THREAD

**Issue by magjac** [pycontribs/jenkinsapi#412]
Hi Guys.

First, thanks for a tremendously useful and well written library!

I have a Jenkins server with almost 10.000 jobs and almost 500.000 builds. I reconfigure these jobs from time to time and that process can take several hours.

I noticed with cProfile and pycallgraph that although I create the Jenkins object only once, jenkinsbase.poll() loads the same jobs over and over again.

I got a huge speedup by using the out-commented lines below:

```python
    def poll(self, tree=None):
#        if not tree and self._data:
#            return self._data
```

Is there a reason for repeating the loading, or is it possible to to a real optimization here?

**Comment by lechat** [comment]
Hi,

The library tries to be up-to-date with Jenkins state, so a lot of places call ``jenkinsbase.poll``(or its override in particular objects) function quite excessively. I've started work in my fork on optimizations and removal of excessive data re-loading, but haven't yet finished.

**Comment by magjac** [comment]
Hi lechat,

what's the status of this. Will yo merge it any time soon? I'm thinking of maybe doing it myself otherwise.

**Comment by magjac** [comment]
Bump

**Comment by lechat** [comment]
The progress is a bit stalled... What I tried to do is to make calls for jobs state to ask only for particular required information and not about whole job. Then I decided to not react on redirects that Jenkins issues after POST and this makes Jenkins not quite stable - tests failing randomly.
Perhaps I need to undo bits of code and continue following redirects or follow redirect and try to  terminate connection after receiving some bytes...
