### ISSUE TITLE
Matrix build with multiple configurations?

### ISSUE THREAD

**Issue by acmay** [pycontribs/jenkinsapi#422]
I have a matrix build setup as "Shelf_Build-amay" with 2 versions of the build and I can't seem to find a way to get the info out of the API.

When I query the downstream builds it is empty. Looking at job._data I see that the info seems to be held in the "activeConfigurations" data like this:
'activeConfigurations': [{'url': 'http://jenkins-srv:8080/jenkins/job/Shelf_Build-amay/target=buildv32/', 'color': 'blue', 'name': 'target=buildv32'}, {'url': 'http://jenkins-srv:8080/jenkins/job/Shelf_Build-amay/target=buildv2/', 'color': 'blue', 'name': 'target=buildv2'}],

I don't see anything in the API that looks up that key.

**Comment by rvernica** [comment]
I would find this feature useful as well. An attempt to something like this has been posted [here](https://stackoverflow.com/a/54413666/418730)
