### ISSUE TITLE
Queue url check in job.py invoke method causes all redirects to fail

### ISSUE THREAD

**Issue by Mitsuwa** [pycontribs/jenkinsapi#444]
I believe there area couple issues with this check
https://github.com/salimfadhley/jenkinsapi/blob/master/jenkinsapi/job.py#L221-L227

### 1:
This redirect url check makes it so that you cant ever redirect the request to jenkins or you're always going to run into this error, because `redirect_url` will never start with `jenkins.baseurl` since the base url is the url that got redirected to whatever redirect_url ends up being.

Also, I think you can get away with just checking for `if 'queue/item' not in redirect_url:` to determine if your url is a Queue URL and it will fix this problem with redirecting.  (Ie example, you post out to http:// but your webserver is setup to redirect all `http://` requests to `https://` - this will fail this check and the exception will be bad because it's not that it's not a queue url - it's because the request got redirected) but that doesn't mean that invoking build is going to fail.

### 2:
```
            if files:
                raise ValueError('Builds with file parameters are not '
                                 'supported by this jenkinsapi version. '
                                 'Please use previous version.')
```

This check is happening inside of the same redirect check statement that really has nothing to do with if there was `build` param passed to the `invoke` method.  Also, this check happens after you've already invoked the build (https://github.com/salimfadhley/jenkinsapi/blob/master/jenkinsapi/job.py#L210-L217).  so it doesn't seem to do anything.

So people using this library and passing `file` to it aren't ever going to hit this exception unless they happen to redirect the requests to a different url than what was a originally passed to create the self.jenkins object.  But even if they do, it's already attempted the build.

If this version actually doesn't support build's with `file`, then the check should be moved to the beginning of the method.  If it Does support build's with `file`, then it should be removed because it's confusing

Here's a diff of what I suggest will fix it.  I'd be happy to make a pr but do not have access rights

```
diff --git a/jenkinsapi/job.py b/jenkinsapi/job.py
index 8e2e463..e1f0ff7 100644
--- a/jenkinsapi/job.py
+++ b/jenkinsapi/job.py
@@ -185,6 +185,11 @@ class Job(JenkinsBase, MutableJenkinsThing):
         if build_params and (not self.has_params()):
             raise BadParams("This job does not support parameters")

+        if files:
+            raise ValueError('Builds with file parameters are not '
+                             'supported by this jenkinsapi version. '
+                             'Please use previous version.')
+
         params = {}  # Via Get string

         if securitytoken:
@@ -218,13 +223,8 @@ class Job(JenkinsBase, MutableJenkinsThing):

         redirect_url = response.headers['location']

-        if not redirect_url.startswith("%s/queue/item" % self.jenkins.baseurl):
-            if files:
-                raise ValueError('Builds with file parameters are not '
-                                 'supported by this jenkinsapi version. '
-                                 'Please use previous version.')
-            else:
-                raise ValueError("Not a Queue URL: %s" % redirect_url)
+        if "queue/item" not in redirect_url:
+            raise ValueError("Not a Queue URL: %s" % redirect_url)
```

**Comment by lechat** [comment]
Anybody can ask for pull request, what do you mean?

1. Redirect url will start with jenkins url that is set in jenkins settings. If your jenkins listens on https, but in settings it is configured to http - you will get that error. See issue #426. Better idea, perhaps, is to add a check in code for mismatch of `http/https` and warn that jenkins is misconfigured.

2. I disagree that `invoke` with file parameter should not start build: there is another way to get to build of that job.
