### ISSUE TITLE
salimfadhley/jenkinsapi vs jenkinsapi/jenkinsapi policy

### ISSUE THREAD

**Issue by dmeunier** [pycontribs/jenkinsapi#454]
Hi,

Could you explain me why the issue https://github.com/salimfadhley/jenkinsapi/issues/448 has been fixed on the salimfadhley/jenkinsapi master branch and has not been in the jenkinsapi/jenkinsapi repository. 

More generally could you tell me what is the policy between these 2 repositories ?

Regards.

**Comment by lechat** [comment]
@salimfadhley ?

**Comment by piwai** [comment]
To complete the original question, it's not clear for us which repo of the two we should use to benefit from the latest bug fixes.
If we check https://github.com/salimfadhley/jenkinsapi/network, we see that most of the activity is done on salimfadhley fork, yet the released version on PyPI comes from the jenkinsapi repo but doesn't include all the commits (for example #448 for Jenkins 2.x compat). IMHO, the releases should either be done directly from salimfadlhey repo, or else the changes on this fork should be merged into the main repo before publishing a new release.

Thanks,

**Comment by lechat** [comment]
Fair point @piwai. I merged this repo into `jenkinsapi/jenkinsapi`.

@salimfadhley, please release new version.

**Comment by salimfadhley** [comment]
This is the main repo. I was the original author of the project, however 99% of the work is done by @lechat . We have a plan to migrate everything to the jenkinsapi/jenkinsapi repo... eventually.

@lechat your wish is my command! :-)

**Comment by lechat** [comment]
@salimfadhley I've heard that moving project to organization using Github magic instead of using git clone/push to org will properly move all issues/PRs there. Never tried that myself though... Worth checking it up, I guess, to remove that hanging duality.

**Comment by piwai** [comment]
Thanks guys for the explanation :)
@salimfadhley Did you release the new version? I can't see it on PyPI...

**Comment by salimfadhley** [comment]
I will do it this week.

**Comment by salimfadhley** [comment]
Release is done. 

I'd like to do the next major release from our new project space. I'd also like to make some changes over there so that the release process is a bit less messy. I'd like to get it into a state where it can be safely handed over.

**Comment by lechat** [comment]
Repository now moved to pycontribs. All releases will go from this new location.
