### ISSUE TITLE
Job.is_running returns False if last build is not running, but other can still be running

### ISSUE THREAD

**Issue by krmarien** [pycontribs/jenkinsapi#461]
When in Jenkins the job history is like this:
 - id 5: completed
 - id 4: running
 - id 3: completed
 - ...

The job.is_running() returns False, however there is still a build of the job running. Is there a way to request only the running builds from Jenkins? Because requesting all builds and looping over these build is not efficient in case of a very large history.

Regards

**Comment by lechat** [comment]
Jenkins REST API doesn't have ability to filter data based on values in maps. So there is no way to ask it to return only builds that are still running. But it is possible to limit amount of information by using tree:

http://localhost:8080/job/my_job/api/json?tree=builds[number,url,building]&pretty=true&depth=2

This will ask Jenkins to return build number, url and status for all jobs:

```
{
  "builds" : [
    {
      "building" : false,
      "number" : 1,
      "url" : "http://localhost:8080/job/my_job/1/"
    }
  ]
}
```
Unfortunately, that case is not handled by ``jenkinsapi`` - when you call `job.is_running()` it will only take last build and check if it is running. Also, we're not getting ``building`` field in ``Job`` object, so you would need to make ``Build`` object for all builds and then ask each build for status. This is very chatty in terms of http requests library would make to Jenkins.

So the best option is to ask Jenkins with above url and process returned dict outside of ``jenkinsapi``.

I will work on optimizing ``Job`` and ``Build`` objects so use cases like yours will be available. But this will take some time.

**Comment by krmarien** [comment]
Thank you for this information. I created a function around the jenkinsapi call that handles this specific case for me.

I completely understand that fixing this would create a bunch of http requests and no everyone will like that. But maybe a small comment in the docs can also "fix" this issue?
