### ISSUE TITLE
Support for categorized-view plugin?

### ISSUE THREAD

**Issue by rafaeleyng** [pycontribs/jenkinsapi#467]
Reading the code for view creation, I see that this type of view is not currently supported.

My question: is this desirable? I would use it right away, but I want to know whether this is inside the scope of jenkinsapi, so I can try to make a PR.

More info: [categorized jobs view](https://wiki.jenkins-ci.org/display/JENKINS/Categorized+Jobs+View)

**Comment by lechat** [comment]
Absolutely desirable! Please make pull request (with unit/system tests).

**Comment by rafaeleyng** [comment]
@lechat Nice. I'm not a Python developer, so I am very clueless about some things. Could you give me an extra quick explanation on how can I test go about testing my changes in the cloned repo against some running Jenkins instance?

I mean, if I change some Python class in the cloned repo on my machine, how can I play with that change. Let's say I changed the `create` method in `Views`, and now I want to create a view using my change against my running Jenkins instance.

**Comment by rafaeleyng** [comment]
I found a way, probably not the best one. Just cloned the repo and dropped a script inside the same folder, so the import will now point to the cloned repo, not to the installed one with pip. If there's a better way, I would like to know.

**Comment by lechat** [comment]
You need to create new virtualenv and then install library to it using `python setup.py develop`. This command will do the same work as `pip install`, but will make python to use local files.

Another way is to not install this library - everything will work from source. 

To test code we use `nose` library. It requires writing system tests and unit tests, they are in `jenkinsapi_tests` folder.

**Comment by rafaeleyng** [comment]
@lechat Nice, could you take a look on what I did so far on #468 ?
