### ISSUE TITLE
Custom Exception "No Build Data" when I try to use get_last_build() on a job instance.  Not sure how to check for build data

### ISSUE THREAD

**Issue by iselenium** [pycontribs/jenkinsapi#472]
Real simple, I just keep running up against an error on jobs we have that don't have any builds, and I can't figure out how to get if there's _any_ build info before I make the call to check status on a build.  Couldn't find anything in the API.

Code:
jenkins_url = '<url>'
server = Jenkins(jenkins_url, username = 'user', password = 'password')

for job_name, job_instance in server.get_jobs():
	print 'Job Name:%s' % (job_instance.name)
	latestBuild=job_instance.get_last_build()
	print latestBuild.get_status()

error:
jenkinsapi.custom_exceptions.NoBuildData: lastBuild

**Comment by lechat** [comment]
If you get that exception - there was no build made. There is nothing wrong in catching that exception in your code and process accordingly.
