### ISSUE TITLE
How to get latest revision which is based on branch

### ISSUE THREAD

**Issue by luisxiaomai** [pycontribs/jenkinsapi#475]
Hi all,

Please help guide how to get latest revision which is based on branch. 
For example, I want to get latest revision from "master" branch.

Thanks 
Luis

**Comment by lechat** [comment]
Build is based on a branch, so you will get latest revision of the branch that was built. 

Build has method `get_revision()` which returns commit and `get_revision_branch()` which returns branch ref.
