### ISSUE TITLE
Is there a way to retrieve timestamped logs for a build through jenkinsapi?

### ISSUE THREAD

**Issue by abcdedf** [pycontribs/jenkinsapi#481]
##### ISSUE TYPE
 - How to...

##### Jenkinsapi VERSION
0.3.1

##### Jenkins VERSION
2.19

##### SUMMARY
I am looking for a way to access timestamped logs. I have timestamper installed and can see timestamped logs in the console output. I am wondering if I can get the timestamped logs through JenkinsApi.

##### USEFUL INFORMATION

```

```

**Comment by lechat** [comment]
I haven't seen any API calls that allow interaction with this plugin. Perhaps it is good idea to ask plugin developers about this feature. If they respond, please reopen this issue.
