### ISSUE TITLE
jenkinsapi.jenkins throws IMPORT MODULE ERRORr OS X 10.10.5/python 2.7.12

### ISSUE THREAD

**Issue by cliffwildman** [pycontribs/jenkinsapi#483]
##### ISSUE TYPE
- Bug Report
##### Jenkinsapi VERSION

Most recent
##### Jenkins VERSION

2.7.2
##### SUMMARY

I'm implementing Jenkins for the first time. Grabbed this tool to build a front end to trigger selenium scripts. 

[Example one](http://pythonhosted.org/jenkinsapi/using_jenkinsapi.html)

shows:

from jenkinsapi.jenkins import Jenkins

this causes an IMPORT MODULE ERROR. 

looking through other pages of the api docs, noticed another method:

from jenkinsapi import jenkinsapi.api

Python command line allowed this and running a check to pull jobs from Jenkins was successful using:

from jenkinsapi.api import Jenkins

Python 2.7.12
MAC OS X 10.10.5
##### EXPECTED RESULTS

For jenkinsapi to work.
##### ACTUAL RESULTS

Throws import module error.
##### USEFUL INFORMATION

Unsure if this is a bug or if the docs need to be updated. Thank you very, very much for this great tool.

**Comment by lechat** [comment]
Cannot reproduce this:

```
 aleksey@rhel72  /tmp/test  virtualenv test     
New python executable in /tmp/test/test/bin/python
Installing setuptools, pip, wheel...done.
 aleksey@rhel72  /tmp/test  source test/bin/activate      
(test)  aleksey@rhel72  /tmp/test  pip install jenkinsapi
Collecting jenkinsapi
  Downloading jenkinsapi-0.3.2-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 5.3MB/s 
Collecting pytz>=2014.4 (from jenkinsapi)
  Using cached pytz-2016.6.1-py2.py3-none-any.whl
Collecting requests>=2.3.0 (from jenkinsapi)
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 522kB 1.9MB/s 
Installing collected packages: pytz, requests, jenkinsapi
Successfully installed jenkinsapi-0.3.2 pytz-2016.6.1 requests-2.11.1
(test)  aleksey@rhel72  /tmp/test  python                
Python 2.7.5 (default, Aug  9 2016, 05:27:46) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from jenkinsapi.jenkins import Jenkins
>>> j = Jenkins('http://localhost:8080')
>>> 
```
From other perspective, this doesn't work:
```
>>> from jenkinsapi import jenkins.api
  File "<stdin>", line 1
    from jenkinsapi import jenkins.api
                                  ^
SyntaxError: invalid syntax
```
This works:
```
>>> from jenkinsapi import api
>>>
```
And that `api` module uses "from jenkinsapi.jenkins import Jenkins"

I don't have Mac to try this on, but I think that something else is missing here...
