### ISSUE TITLE
'requests.exceptions.SSLError' when try to connect via 'https'

### ISSUE THREAD

**Issue by olegeech** [pycontribs/jenkinsapi#484]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

'requests.exceptions.SSLError' when try to connect via 'https'

##### EXPECTED RESULTS

Possibiliy to establish secure http connection.

##### ACTUAL RESULTS

```
import jenkinsapi
from jenkinsapi.jenkins import Jenkins

J = Jenkins('https://JenkinsCI.com')
```
When I'm trying to connect via 'https' then I get an error: "...requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)"
and no way to establish secure http connection.

##### USEFUL INFORMATION

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/jenkinsapi/jenkins.py", line 43, in __init__
    JenkinsBase.__init__(self, baseurl)
  File "/usr/lib/python2.7/dist-packages/jenkinsapi/jenkinsbase.py", line 33, in __init__
    self.poll()
  File "/usr/lib/python2.7/dist-packages/jenkinsapi/jenkinsbase.py", line 55, in poll
    self._data = self._poll()
  File "/usr/lib/python2.7/dist-packages/jenkinsapi/jenkinsbase.py", line 59, in _poll
    return self.get_data(url)
  File "/usr/lib/python2.7/dist-packages/jenkinsapi/jenkinsbase.py", line 63, in get_data
    response = requester.get_url(url, params)
  File "/usr/lib/python2.7/dist-packages/jenkinsapi/utils/requester.py", line 89, in get_url
    return requests.get(self._update_url_scheme(url), **requestKwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)
```

**Comment by ripcurld00d** [comment]
Are you using a self signed certificate?

**Comment by olegeech** [comment]
No

**Comment by ripcurld00d** [comment]
Even though, it is not a problem on the jenkins-api side.
You can do two things:
 1. Set `ssl_verify` to False when calling jenkinsapi.jenkins.Jenkins (**not recommended**)
 2. Figure out what is wrong with the Jenkins master certificate.

To make sure this problem is related to the Jenkins master, try to run:
```
import requests
resp = requests.get(jenkins_url)
print resp.status_code
```
where jenkins_url is the full URL to the Jenkins master (e.g. https://jenkins.mycorp.io)
My guess is you will get an exception.

**Comment by lechat** [comment]
As @ripcurld00d explained, this is not an issue with `jenkinsapi`. Closing this.

**Comment by olegeech** [comment]
Thanks, but how can I set 'ssl_verify' to False in jenkinsapi?

**Comment by lechat** [comment]
Pass the parameter to Jenkins: https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi/jenkins.py#L43

**Comment by ripcurld00d** [comment]
More specific example:

```
from jenkinsapi.jenkins import Jenkins

client = Jenkins('https://jenkins.mycorp.io', ssl_verify=False)
client.version()
```

**Comment by olegeech** [comment]
I tried to this earlier but got the following error:
``
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'ssl_verify'
``

**Comment by lechat** [comment]
Which version of jenkinsapi you are using?

**Comment by olegeech** [comment]
I installed it using 'apt-get install python-jenkinsapi' command.
It seems 'python-jenkinsapi_0.2.16'

**Comment by lechat** [comment]
The `ssl_verfy` parameter was not present in this version. I am not exactly sure who maintains deb packages...

**Comment by ripcurld00d** [comment]
@olegeech you can always use `virtualenv` and install the updated version using `pip`.

**Comment by olegeech** [comment]
Thanks! I've alredy installed it.

**Comment by lechat** [comment]
Did it work as expected?

**Comment by olegeech** [comment]
Yes, thanks!

Best regards,
Oleg Tatarchuk
