### ISSUE TITLE
jenkinsapi fails to load objects when blanket /api/python is filtered

### ISSUE THREAD

**Issue by jswager** [pycontribs/jenkinsapi#485]
##### ISSUE TYPE
- Bug Report
##### Jenkinsapi VERSION

0.3.2
##### Jenkins VERSION

CloudBees Enterprise Jenkins 
1.651.3.1
##### SUMMARY

Working with CloudBees to reduce load on our fairly large Jenkins server. One solution they have is to block "blanket API request" by using the Filter plugin to block any simple request to /api/(json|xml|python) unless the request is accompanied by a "?depth=x" or "?tree=xxx" sort of query.  The idea being that large, potentially CPU intensive queries would be blocked.

Many of the function, object constructors in jenkinsapi will do a poll() with a blank.  That will trigger a /api/python call, which will get blocked on these systems.  If the script has a specific object already, it can do a poll(tree=[something]) and obtain data on the object.
##### EXPECTED RESULTS

Ideally, a way to get the data even with the filter in place.  Perhaps by adding a default tree=[something] value to default poll() values.
##### ACTUAL RESULTS

Exceptions were raised when Jenkins responded back with a non-200 error code.
##### USEFUL INFORMATION

Enable filtering with a non-200 value on /api/python and try to load a specific job via the Jenkins API.

```
Sorry, no stack was preserved
```

**Comment by jswager** [comment]
For reference, this is the CloudBees article on the filtering: https://www.cloudbees.com/blog/taming-jenkins-json-api-depth-and-tree

And we are using a filter of: 
```
^/((?!crumbIssuer).*/api/(python|json|xml)$|.*/api/(python|json|xml)\?depth=([456789]|[0-9][^&]))
```

**Comment by lechat** [comment]
Most of the major calls, like initial call to load jobs when `Jenkins` object is connecting to server, are already use `tree=[]`, but not depth. But there are some calls still use blanket call purely because adding `tree` will remove essential attibutes and adding them back in `tree` seems like overkill.

But it would be interesting to see which calls CloudBees threat as CPU intensive. 

I will take a look how library works with Filter plugin.

**Comment by lechat** [comment]
Can't find Filter plugin in Jenkins plugins... Could you give me a link to it?

**Comment by jswager** [comment]
Documentation is non-existent really; this was all I could find: https://release-notes.cloudbees.com/product/CloudBees+Request+Filter+Plugin

During one of their support tickets, they recommended using it since many of "slow requests" were coming from api calls.  We have a rather large system.

**Comment by lechat** [comment]
Hi @jswager 

I've made a bunch of changes, all in "get_tree" branch. Could you give it a go and see if that works better in your Jenkins?
