### ISSUE TITLE
support getting environment variables

### ISSUE THREAD

**Issue by t0ffel** [pycontribs/jenkinsapi#489]
##### ISSUE TYPE
- Feature Idea
##### Jenkins VERSION

2.9
##### SUMMARY

The REST API to get env variables from the build is present.
I think it would be great if jenkinsapi supported getting these variables.
https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin

**Comment by lechat** [comment]
This request better to be directed to creators of that plugin. AFAIK, that plugin doesn't have any REST API and doesn't contribute to build structure.

**Comment by t0ffel** [comment]
@lechat for api you can call:
curl -X GET -H"Accept:application/json" <jenkins_url>/job/<job_name>/18/injectedEnvVars/export
or <jenkins_url>/job/<job_name>/18/injectedEnvVars/api/python

What I'm trying to accomplish is to obtain the env variables that contain some specific information from Jenkins' env variables for the particular run. Can you possibly advise another way of accomplishing this?

**Comment by lechat** [comment]
Interesting... I will add method to `Build` object to get them.

**Comment by ripcurld0** [comment]
@lechat calling dibs. Do you mind if I work on this?

**Comment by lechat** [comment]
Sure! You don't need to ask my permission. :)

**Comment by ripcurld0** [comment]
Hi @lechat

Cool :beer: ... I guess it will take me less than two days for posting a PR.

Thanks.
/cc @t0ffel

**Comment by woqer** [comment]
+1
