### ISSUE TITLE
Fail to update headers using CrumbRequester

### ISSUE THREAD

**Issue by frederiksdun** [pycontribs/jenkinsapi#491]
##### ISSUE TYPE
 - Bug Report

##### Jenkinsapi VERSION
0.3.2

##### Jenkins VERSION
2.17

##### SUMMARY
I created a minimal Jenkins freestyle job which accepts a file parameter foobar:
```xml
    <?xml version='1.0' encoding='UTF-8'?>
    <project>
      <description></description>
      <keepDependencies>false</keepDependencies>
      <properties>
        <hudson.model.ParametersDefinitionProperty>
          <parameterDefinitions>
            <hudson.model.FileParameterDefinition>
              <name>foobar</name>
              <description></description>
            </hudson.model.FileParameterDefinition>
          </parameterDefinitions>
        </hudson.model.ParametersDefinitionProperty>
      </properties>
      <scm class="hudson.scm.NullSCM"/>
      <canRoam>true</canRoam>
      <disabled>false</disabled>
      <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
      <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
      <triggers/>
      <concurrentBuild>false</concurrentBuild>
      <builders/>
      <publishers/>
      <buildWrappers/>
    </project>
```
If I try to invoke this job using attach test.py I get the following backtrace:
##### EXPECTED RESULTS
Job is executed and file is uploaded

##### ACTUAL RESULTS
Backtrace is shown

##### USEFUL INFORMATION

Test code:
[test.txt](https://github.com/pycontribs/jenkinsapi/files/471453/test.txt)

    Fetched crumb: blablabla
    Traceback (most recent call last):
      File "./test.py", line 21, in <module>
        j.invoke(block=True, files={'foobar': open(args.file_name)})
      File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/job.py", line 214, in invoke
        allow_redirects=False
      File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/utils/requester.py", line 135, in     post_and_confirm_status
        allow_redirects)
      File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/utils/crumb_requester.py", line 29, in post_url
        self._last_crumb_data, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/utils/crumb_requester.py", line 50, in _post_url_with_crumb
        headers.update(crumb_data)
    AttributeError: 'NoneType' object has no attribute 'update'

**Comment by lechat** [comment]
This is now fixed.
