### ISSUE TITLE
Node attributes are not being populated

### ISSUE THREAD

**Issue by rgov** [pycontribs/jenkinsapi#495]
##### ISSUE TYPE
- Bug Report
##### Jenkinsapi VERSION

0.3.2
##### Jenkins VERSION

2.7.2
##### SUMMARY

`jenkinsapi.node.node_attributes` is not being populated.
##### EXPECTED RESULTS

```
for name, node in jenkins.nodes.iteritems():
  print name, node.node_attributes
```

Should print each of my nodes, and their attributes.
##### ACTUAL RESULTS

This prints `<nodename> {}` for each node. Calling `node.get_node_attributes()` raises an exception because the `node_description` key is missing.

**Comment by lechat** [comment]
What is the use case for node attributes? 

Current method is a helper that defined node structure for `Nodes.create_node` only.
