### ISSUE TITLE
build_job function retrieve HTTP Error 400: Nothing is submitted 

### ISSUE THREAD

**Issue by KursLabIgor** [pycontribs/jenkinsapi#498]
##### ISSUE TYPE
 - Bug Report
##### Jenkinsapi VERSION
0.3.2
##### Jenkins VERSION
2.72
##### SUMMARY
build_job function retrieve HTTP Error 400: Nothing is submitted 

##### EXPECTED RESULTS
job with passed name should be started at the server

##### ACTUAL RESULTS
Error: HTTP Error 400: Nothing is submitted

##### USEFUL INFORMATION

##For bugs, show exactly how to reproduce the problem.
##For new features, show how the feature would be used.
##I have class connector 
import jenkins as jens

 server = jens.Jenkins(**jenkins_config)
print("Connected to Jenkins version " + server.get_version())
## Then get all job list and by specific condition pass job name to build_job function 
self.build_job(name, parameters=None)
where 'name' - Unicode string name of job.

```
absent
```

**Comment by lechat** [comment]
```
from jenkinsapi.jenkins import Jenkins

server = Jenkins('http://localhost:8080')
server.build_job('my_job')
```
or
```
from jenkinsapi.jenkins import Jenkins

server = Jenkins('http://localhost:8080')
job = server['my_job']
queue_item = job.invoke()
queue_utem.block_until_complete()
build = queue_item.get_build()
```

**Comment by KursLabIgor** [comment]
OK. probuyu. sps


>Вторник, 20 сентября 2016, 15:44 +03:00 от Aleksey Maksimov <notifications@github.com>:
>
>from jenkinsapi.jenkins import Jenkins

server = Jenkins('http://localhost:8080')
server.build_job('my_job')
>or
>from jenkinsapi.jenkins import Jenkins

server = Jenkins('http://localhost:8080')
job = server['my_job']
queue_item = job.invoke()
queue_utem.block_until_complete()
build = queue_item.get_build()

**Comment by KursLabIgor** [comment]
works correctly. sorry my bad.
