### ISSUE TITLE
Request for new release 0.3.3?

### ISSUE THREAD

**Issue by scoheb** [pycontribs/jenkinsapi#499]
##### ISSUE TYPE
 - Request

##### SUMMARY
Would it be possible to create a new release so that we can use build.get_params()?

**Comment by bmwant** [comment]
I believe we will release new version soon. It would be reasonable with [this latest changes](https://github.com/pycontribs/jenkinsapi/pull/507). 
Right, @lechat ?

**Comment by daveFNbuck** [comment]
I also need a new release so I can fetch artifacts again now that #458 is resolved.

**Comment by lechat** [comment]
Released!

**Comment by daveFNbuck** [comment]
Thanks!

**Comment by daveFNbuck** [comment]
Somehow the 0.3.3 release missed my changes. It didn't cause me problems until I started messing with the deploy again today. I also found a new bug that I don't know how to fix :(
