### ISSUE TITLE
Add support for downloading files from the workspace of a build

### ISSUE THREAD

**Issue by djonsson** [pycontribs/jenkinsapi#509]
Feature Idea

I was looking into using the api to download files from the workspace of a job (not the artifact), and from what I can see, I didn't find this implemented. Is there a reason for not supporting it, or could it be added to the api?

**Comment by lechat** [comment]
I guess that none of contributors needed that feature, so nobody worked on it. You are welcome to submit pull request for it.

**Comment by salimfadhley** [comment]
I suspect that it might not actually be possible to do this - Jenkins
doesn't provide a mechanism for accessing the workspace. Typically there is
more than one workspace and they live on remote machines.

**Comment by lechat** [comment]
@salimfadhley There is a workspace browser in each job and files are accesible for browser, so it shall be possible to get them via python code.

**Comment by yerravenkataramana** [comment]
how i have to get pom.ml into  git hub to build the code in jenkins
