### ISSUE TITLE
Where can I find the detailed documentation of some objects?

### ISSUE THREAD

**Issue by LucasAmorimSilva** [pycontribs/jenkinsapi#510]
I am beginning today to use the Jenkins API and I can't find the documentation of some objects.
In this link:
https://jenkinsapi.readthedocs.io/en/latest/using_jenkinsapi.html

I have this example:

```
"""Disable a Jenkins job"""
def disable_job():
    # Refer Example #1 for definition of function 'get_server_instance'
    server = get_server_instance()
    job_name = 'nightly-build-job'
    if (server.has_job(job_name)):
        job_instance = server.get_job(job_name)
        job_instance.disable()
        print 'Name:%s,Is Job Enabled ?:%s' % (job_name,job_instance.is_enabled())
```

But I couldn't find where the object server is documented. I want to know all its methods etc.
Can any one help?

Thanks!!!

**Comment by lechat** [comment]
Existing documentation is not complete. Contributions on it are welcome! 

`get_server_instance()` here is this:

```
from jenkinsapi.jenkins import Jenkins


server = Jenkins('http://localhost:8080', 'username', 'password)
```

Better examples are in `examples` folder of this repo.
