### ISSUE TITLE
ValueError "Not a Queue URL" exception triggered wrongly after invoking a job.

### ISSUE THREAD

**Issue by thibaudrobelain** [pycontribs/jenkinsapi#513]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When starting a build from a job invocation, a ValueError("Not a Queue URL: %s" % redirect_url) is triggered because the redirect_url is not in the expected format. This is because my Jenkins host is set to an HTTPS base URL and the redirect_url starts with HTTP only.

##### EXPECTED RESULTS
No exception because there's a valid URL returned. Unfortunately it seems like the API picks up a redirect_url that is HTTP and not HTTPS as my Jenkins base URL.

##### ACTUAL RESULTS
ValueError raised because this check triggers it:
`if not redirect_url.startswith("%s/queue/item" % self.jenkins.baseurl):` 
https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi/job.py L214

```
jenkins = Jenkins("https://...")
jenkins['My-Job'].invoke(securitytoken=MY_TOKEN, build_params=params)
```

I'm open to the idea of submitting a PR to fix this if we agree on a behavior!

**Comment by lechat** [comment]
Please check your Jenkins configuration. If it is properly configured - it will not return http url if you access it via https.

**Comment by pingwhistle** [comment]
I suspect it must be a Jenkins issue. On my instance, we use HTTPS terminated by Apache, which is then proxied through to Jenkins via HTTP. All URLS are configured correctly in Jenkins to specify https://jenkinsserver, and we handle the HTTP to HTTPS redirect in Apache. Works without any issues.

POSTS to the <job>/build API endpoint would include a location header to http://jenkinserver, which is probably what jenkinsapi is checking above.

I was able to workaround the issue by editing the location header in Apache:

`    Header edit Location ^http://jenkinserver/ https://jenkinserver/
`

As per http://wiki.hudson-ci.org/display/HUDSON/Running+Hudson+behind+Apache

**Comment by MrKiven** [comment]
so, how to fix it?

**Comment by lechat** [comment]
Fix is to configure Jenkins url properly in Jenkins settings. This is not an issue for `jenkinsapi`, but Jenkins configuration issue.

**Comment by mattvonrocketstein** [comment]
Jenkins was setup with the correct https URL for me, but I had to add this to nginx proxy configs before it work: `proxy_set_header        X-Forwarded-Proto $scheme;`.  I understand wanting to push it up the stack but this still feels like a library bug honestly.. the library is given one URL initially, but then switches to another.  If that is really desirable for some reason, maybe the library could also change to honor redirects?

**Comment by lechat** [comment]
Library gets that url from Jenkins itself. The initial url is not used anywhere besides initial connect to Jenkins.

**Comment by trqlcgcg** [comment]
Jenkins version:2.176.2
error	14-Dec-2020 16:43:56	Traceback (most recent call last):
error	14-Dec-2020 16:43:56	  File "./attest/scripts/TestServiceJenkins.py", line 173, in <module>
error	14-Dec-2020 16:43:56	    main(sys.argv)
error	14-Dec-2020 16:43:56	  File "./attest/scripts/TestServiceJenkins.py", line 170, in main
error	14-Dec-2020 16:43:56	    sys.exit(submit_job())
error	14-Dec-2020 16:43:56	  File "./attest/scripts/TestServiceJenkins.py", line 110, in submit_job
error	14-Dec-2020 16:43:56	    qi = j.invoke(build_params=job_args)
error	14-Dec-2020 16:43:56	  File "/users/bbcur/synced_repos/interface_scripts/attest/python/lib/python3.8/site-packages/jenkinsapi/job.py", line 215, in invoke
error	14-Dec-2020 16:43:56	    raise ValueError("Not a Queue URL: %s" % redirect_url)
error	14-Dec-2020 16:43:56	**ValueError: Not a Queue URL: http://x286646:8080/queue/item/171/**


My Jenkins v2.176.2 instance is running http.  The exception is raised but the URL looks correct.   The JenkinsAPI version is 0.3.7.   I'm running Python 3.8.

When I curl the command the 'location' comes back exactly as http://x286646:8080/queue/item/xxx/  format.  But invoking using job.invoke raise exception.

Any Ideas?
