### ISSUE TITLE
invoke to upload file and parameters, but the parameters not update with uploading file ok

### ISSUE THREAD

**Issue by zh794390558** [pycontribs/jenkinsapi#516]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION
'0.3.2'

##### Jenkins VERSION
Jenkins ver. 1.647

##### SUMMARY
 invoke to upload file and parameters,  the parameters not update with uploading file ok, and the jenkinsapi return OK, the response is 201 but the build web's param is not updated.

the problem is same to "Invoking job with both build_params and files doesn't work as expected #280"

and the same code can work well on Jenkins ver. 1.656

##### EXPECTED RESULTS
I wang the file is uploaded and the parameter is passed ok 

##### ACTUAL RESULTS
File is uploaded but the parameter is not passed .
But when i use ivoke to only passing paramets,  the params is updated ok .

##### USEFUL INFORMATION

old job 203, new job 204
{'allow_redirects': True,
 
 'params': {'tree': 'jobs[name,color,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'allBuilds[number,url]'},
 'stream': False,
 'verify': True}
{'parameter': [{'name': 'BEGIN_SIL', 'value': '50'},
               {'name': 'CHANNELS', 'value': '1'},
               {'name': 'END_SIL', 'value': '50'},
               {'name': 'FILE_TYPE', 'value': 'pcm'},
               {'name': 'SAMPLE_RATE', 'value': '16000'},
               {'name': 'SPEAKER', 'value': 'standard_female'},
               {'name': 'VERSION', 'value': 'v2.1.1'},
               {'name': 'VOICE_SPEED', 'value': '70'},
               {'name': 'VOICE_VOLUMN', 'value': '50'},
               {'file': './input.txt', 'name': './input.txt'}]}
{'BEGIN_SIL': '50',
 'CHANNELS': '1',
 'END_SIL': '50',
 'FILE_TYPE': 'pcm',
 'SAMPLE_RATE': '16000',
 'SPEAKER': 'standard_female',
 'VERSION': 'v2.1.1',
 'VOICE_SPEED': '70',
 'VOICE_VOLUMN': '50',
 'json': '{"redirectTo": ".", "parameter": [{"name": "BEGIN_SIL", "value": "50"}, {"name": "CHANNELS", "value": "1"}, {"name": "END_SIL", "value": "50"}, {"name": "FILE_TYPE", "value": "pcm"}, {"name": "SAMPLE_RATE", "value": "16000"}, {"name": "SPEAKER", "value": "standard_female"}, {"name": "VERSION", "value": "v2.1.1"}, {"name": "VOICE_SPEED", "value": "70"}, {"name": "VOICE_VOLUMN", "value": "50"}, {"name": "./input.txt", "file": "./input.txt"}], "statusCode": "303"}'}
'======================='
{'token': 'xxxxxxxxxxxxxxxxx'}
{'allow_redirects': False,
 
 'data': {'BEGIN_SIL': '50',
          'CHANNELS': '1',
          'END_SIL': '50',
          'FILE_TYPE': 'pcm',
          'SAMPLE_RATE': '16000',
          'SPEAKER': 'standard_female',
          'VERSION': 'v2.1.1',
          'VOICE_SPEED': '70',
          'VOICE_VOLUMN': '50',
          'json': '{"redirectTo": ".", "parameter": [{"name": "BEGIN_SIL", "value": "50"}, {"name": "CHANNELS", "value": "1"}, {"name": "END_SIL", "value": "50"}, {"name": "FILE_TYPE", "value": "pcm"}, {"name": "SAMPLE_RATE", "value": "16000"}, {"name": "SPEAKER", "value": "standard_female"}, {"name": "VERSION", "value": "v2.1.1"}, {"name": "VOICE_SPEED", "value": "70"}, {"name": "VOICE_VOLUMN", "value": "50"}, {"name": "./input.txt", "file": "./input.txt"}], "statusCode": "303"}'},
 'files': {'./input.txt': <open file './input.txt', mode 'r' at 0x7f6f063cbd20>},
 'params': {'token': 'xxxxxxxxxxxxx'},
 'verify': True}
<Response [201]>
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'jobs[name,color,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'allBuilds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'builds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'allBuilds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'lastBuild[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'depth': 1},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'depth': 1, 'tree': 'building'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'depth': 1, 'tree': 'building'},
 'stream': False,
 'verify': True}
building WavGenerator 204 ...
save console_output
download 204 artifcats to ./output
{'allow_redirects': True,
 
 'params': {'tree': 'jobs[name,color,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'jobs[name,color,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'allBuilds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'builds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'allBuilds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'lastBuild[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'depth': 1},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'depth': 1, 'tree': 'artifacts[relativePath,fileName]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'jobs[name,color,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'jobs[name,color,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'allBuilds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'builds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'allBuilds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'lastBuild[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'depth': 1},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'depth': 1, 'tree': 'artifacts[relativePath,fileName]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'stream': True,
 'verify': True}
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
ERROR:root:Failed request at http:///fingerprint/c8a7205139e54d6aaf3a5b81878cdc4f/api/python with params: None 
WARNING:root:MD5 cannot be checked if fingerprints are not enabled
{'allow_redirects': True,
 
 'params': {'tree': 'jobs[name,color,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'jobs[name,color,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'allBuilds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'builds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'allBuilds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'lastBuild[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'depth': 1},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'depth': 1, 'tree': 'artifacts[relativePath,fileName]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'stream': True,
 'verify': True}
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
ERROR:root:Failed request at http://:/fingerprint/71a006fc2556f3a973c039c06e805d93/api/python with params: None 
WARNING:root:MD5 cannot be checked if fingerprints are not enabled
{'allow_redirects': True,
 
 'params': {'tree': 'jobs[name,color,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'jobs[name,color,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'allBuilds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'builds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'allBuilds[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'tree': 'lastBuild[number,url]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'depth': 1},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'params': {'depth': 1, 'tree': 'artifacts[relativePath,fileName]'},
 'stream': False,
 'verify': True}
{'allow_redirects': True,
 
 'stream': True,
 'verify': True}
{'allow_redirects': True,
 
 'stream': False,
 'verify': True}
ERROR:root:Failed request at http://:/fingerprint/1c29a1dd2cb717532541440e6bc5522a/api/python with params: None 
WARNING:root:MD5 cannot be checked if fingerprints are not enabled
build success

```
from jenkinsapi import job
j = jenkinsapi.jenkins.Jenkins(self.config['jobs'][self.job_sub_name]['srvurl'], self.config['jobs'][self.job_sub_name]['auth']['username'],
                                self.config['jobs'][self.job_sub_name]['auth']['token'])

upload_file = open(self.config['jobs'][self.job_sub_name]['file_location'], 'r')

mjob = job.Job(url=self.job_url, name=self.job_name, jenkins_obj=j)

mjob.invoke(securitytoken=self.config['jobs'][self.job_sub_name]['auth']['token'] ,block=True, build_params=self.param[self.param['paramid']],
            files={str(self.config['jobs'][self.job_sub_name]['file_name']) : upload_file})

upload_file.close()

```

**Comment by zh794390558** [comment]
The problem can fix by change url=u'http://10.10.10.1:8142/job/project/buildWithParameters' to 
url=u'http://10.10.10.1:8142/job/project/build'. But the jenkinsapi can not handle well in invoke, so i change      the ivoke function,  and i will commit soon.

But I do not known the difference between with buildWithParameters and build.

**Comment by lechat** [comment]
There is a test (https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi_tests/systests/test_parameterized_builds.py#L96) that triggers job with parameter and file parameter. And it is passing ok.

I am also not sure where did you get that huge "useful infomation" blob from and I don't recognise it.

**Comment by zh794390558** [comment]
I have use that interface on other jenkins that is very well, but when use it on another jenkins is not work as before, and the interface is passed without any error, but the params is not passed and file is also not uploaded. Then I make a test on build not buildwithparam, that is work well as I wanted.

**Comment by lechat** [comment]
What is the difference between those two jenkins servers? Jenkins version?

**Comment by zh794390558** [comment]
I don't known the difference between them , but the well Jenkins version is ver. 1.656,  the other one is  ver. 1.647 which is not work as expect.  And also the two Jenkins servers are in different city and maintained by different team.

**Comment by melkamar** [comment]
Can confirm, when using `job.invoke()` with only parameters, they are passed correctly. When using both parameters and files, only files are uploaded, no parameters.

This is happening for Jenkins version 1.643. Other instances (2.x+) work fine.
