### ISSUE TITLE
Possible Jenkins server access issue

### ISSUE THREAD

**Issue by tzili** [pycontribs/jenkinsapi#519]
#####  Jenkinsapi VERSION
0.2.30 (0.3.3 might be affected in the same way)

#####  Jenkins VERSION
2.7.2

#####  ISSUE TYPE
bug/feature

#####  SUMMARY 
If an user outside a specific network tries to access the Jenkins server using the server IP or FQDM and the server refers to itself by the hostname, a ConnectionError is raised.

##### ACTUAL RESULTS
*** ConnectionError: HTTPConnectionPool(host='<some_hostname>', port=<some_port>): Max retries exceeded with url: /job/<some_job>/api/python (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x121F1E30>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

##### IN DETAIL
By, 'server refers to itself' I mean the addresses used to target different jobs as they appear in <server>/api/python. 

In this case, the users can access Jenkins manually from the browser but not using python scripting. 

The Jenkins server address used at the time of calling Jenkins() is used to get access to the API, but further when details about different jobs are needed, the addresses for these jobs are obtained from the API. If the server refers to itself with the hostname, any user from outside the network, will not be able to go further.
Of course, the issue could be solve by configuring Jenkins to use the FQDM instead of hostname.
I do not know if this is really a bug, but I just wanted to let you know.

The problem might get solved if the following fix is applied (note: it was not tested yet):
In jenkinsbase.py,
In function poll(),
After line 60,
Add:
```
for item in data['jobs']:
item['url'] = item['url'].replace("<whatever_hostname_is_there>", self.baseurl)
```

**Comment by lechat** [comment]
This problem is usually caused by Jenkins configuration. There is an option in "Manage Jenkins" screen that sets Jenkins URL. If URL is not set properly, ie the way that Jenkins would be reachange for all users, then some clients and jenkinsapi will fail.

**Comment by guysoft** [comment]
This drove me crazy, it should really be documented somewhere
