### ISSUE TITLE
get_resultset() throws an exception

### ISSUE THREAD

**Issue by KJX16** [pycontribs/jenkinsapi#520]
##### ISSUE TYPE

 - How To
##### Jenkinsapi VERSION
0.3.3
##### Jenkins VERSION
1.577
##### SUMMARY
I was able to do several queries successfully:
>>> import jenkinsapi
>>> from jenkinsapi.jenkins import Jenkins
>>> J=Jenkins("http://jenkins.xyz.com:8080")
>>>job=J['abc']
>>>build=job.get_last_good_build()
>>>build
<jenkinsapi.build.Build abc#584>
>>>url = build.get_result_url()
>>>url
'http://jenkins.xyz.com:8080/job/abc/584/testReport/api/python'

However when I tried to get result set for the build, I got an exception:
>>>r=build.get_resultset()
ERROR:root:Failed request at http://jenkins.xyz.com:8080/job/abc/584/testReport/api/python with params: None 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.11-intel/egg/jenkinsapi/build.py", line 405, in get_resultset
  File "build/bdist.macosx-10.11-intel/egg/jenkinsapi/result_set.py", line 22, in __init__
  File "build/bdist.macosx-10.11-intel/egg/jenkinsapi/jenkinsbase.py", line 35, in __init__
  File "build/bdist.macosx-10.11-intel/egg/jenkinsapi/jenkinsbase.py", line 59, in poll
  File "build/bdist.macosx-10.11-intel/egg/jenkinsapi/jenkinsbase.py", line 69, in _poll
  File "build/bdist.macosx-10.11-intel/egg/jenkinsapi/jenkinsbase.py", line 83, in get_data
  File "/Library/Python/2.7/site-packages/requests/models.py", line 884, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://jenkins.xyz.com:8080/job/abc/584/testReport/api/python

##### EXPECTED RESULTS
Detailed results for the build.

##### ACTUAL RESULTS
Exception above

##### USEFUL INFORMATION

```
As in Summary.
```

**Comment by KJX16** [comment]
Any thoughts on this issue? I tried to use a username and password to login when initializing the Jenkins object and got the same result with get_resultset(), any configuration I should do to avoid it? Thanks.

**Comment by lechat** [comment]
I haven't investigated what is happening with library code, but just want to point that Jenkins version you use is quite old and is not one of the stable (LTS) versions.

**Comment by KJX16** [comment]
Thanks for the feedback! Yeah, we have been using it for a while, since it has been pretty stable, we haven't  thought about updating it, I'll check if we can do something about it. At the same time, if you could confirm the get_resultset() works for updated version, that will be helpful.

**Comment by lechat** [comment]
Do you have JUnit publisher in your job?

What happens if you go to http://jenkins.xyz.com:8080/job/abc/584/testReport/api/python in your browser?

**Comment by KJX16** [comment]
Thanks! JUnit is not used as publisher, Robot Test Framework is used as the publisher. http://jenkins.xyz.com:8080/job/abc/584/testReport/api/python shows a Jason object related to the test config and high level result(here is a small portion of it): 
"fullDisplayName":"abc #584","id":"2016-11-28_02-24-49","keepLog":False,"number":584,"result":"SUCCESS","builtOn":"pelardoning",...

The Json object looks complete, Is that get_resultset() tries to retrieve?
