### ISSUE TITLE
adopting the start_parameterized_build.py example gives 'No valid crumb was included in the request'

### ISSUE THREAD

**Issue by dothebart** [pycontribs/jenkinsapi#526]
##### ISSUE TYPE
 - Bug Report when triggering a build with jenkins 2:

##### Jenkins VERSION
Jenkins 2.34
##### SUMMARY
when trying to trigger a build, an error is thrown.
##### EXPECTED RESULTS
the build should start
##### ACTUAL RESULTS
```
    qi = job.invoke(build_params=params)
  File "/usr/local/lib/python3.5/dist-packages/jenkinsapi/job.py", line 214, in invoke
    allow_redirects=False
  File "/usr/local/lib/python3.5/dist-packages/jenkinsapi/utils/requester.py", line 148, in post_and_confirm_status
    response.text.encode('UTF-8')
jenkinsapi.custom_exceptions.JenkinsAPIException: Operation failed. url=https://master.jenkins.arangodb.info/job/test%20fedora/buildWithParameters, data={'json': '{"redirectTo": ".", "statusCode": "303", "parameter": {"value": "True", "name": "SKIP_BUILD"}}', 'SKIP_BUILD': True}, headers={'Content-Type': 'application/x-www-form-urlencoded'}, status=403, text=b'<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>\n<title>Error 403 No valid crumb was included in the request</title>\n</head>\n<body><h2>HTTP ERROR 403</h2>\n<p>Problem accessing /job/test%20fedora/buildWithParameters. Reason:\n<pre>    No valid crumb was included in the request</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>\n\n</body>\n</html>\n'
```

##### USEFUL INFORMATION
It seems this issue is about similar problems:
https://github.com/jan-molak/jenkins-build-monitor-plugin/issues/215
Another Hint from the jenkins wiki: 
https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API#RemoteaccessAPI-CSRFProtection

**Comment by lechat** [comment]
You need to use CrumbRequester when initialising Jenkins object. Look at the Test_crumb_requester test for usage example.

**Comment by dothebart** [comment]
I'm a bit out of luck getting this working; I've tried: 

    jenkins = Jenkins('https://myjenkins', username='willi', password='passvoid'');

    crumbed = Jenkins(
        jenkins.baseurl,
        requester=CrumbRequester(baseurl=jenkins.baseurl)
    )

and it gives me: 

    requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myjenkins/api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D

Sending the ENABLE_CRUMBS_CONFIG document first, only gives `No valid crumb` again:

    jenkins.requester.post_and_confirm_status(
     urljoin(jenkins.baseurl, '/configureSecurity/configure'),
     data={
         'Submit': 'save',
         'json': json.dumps(ENABLE_CRUMBS_CONFIG)
     },
     headers={'Content-Type': 'application/x-www-form-urlencoded'}
     )

**Comment by pilgrim2go** [comment]
I got the same issue. Then tried 
https://wiki.jenkins-ci.org/display/JENKINS/CSRF+Protection
to disable crumb.
It's now working

**Comment by dothebart** [comment]
hm, yes turning it of may be a short way around it, but in the end it should work :-(

Now the build is triggered, however, 

    # Block this script until build is finished
    if qi.is_queued() or qi.is_running():
        qi.block_until_complete()

doesn't work, since qi doesn't have these methods: (so I guess the example is wrong?) 

['RETRY_ATTEMPTS', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_data', '_poll', 'baseurl', 'block_until_building', 'block_until_complete', 'get_build', 'get_build_number', 'get_data', 'get_jenkins_obj', 'get_job', 'get_job_name', 'get_parameters', 'is_running', 'jenkins', 'name', 'poll', 'pprint', 'process_job_folder', 'python_api_url', 'queue_id', 'resolve_job_folders', 'strip_trailing_slash', 'why']

**Comment by pilgrim2go** [comment]
Yes. The example is wrong :).
I haven't tried it but following old school way
```
		job.invoke(build_params=params,block=True)

		build = job.get_last_build()
		while build.is_running():
			time.sleep(0.25)
```

**Comment by dothebart** [comment]
yes, got it mostly do what I want:
  https://github.com/dothebart/jsh
remove the browser mouse clickediclick from my workflow when working on jenkins jobs development.

Getting the CSRF Protection working would be nice.

**Comment by lechat** [comment]
It is working already, the problem is in bad design of the use of Requesters: you need to pass to Requester all parameters that you're passing to Jenkins.

```
jenkins = Jenkins('https://myjenkins', username='willi', password='passvoid', requester=CrumbRequester(username='willi', password='passvoid', baseurl='https://myjenkins'))
```

See also #121

**Comment by dothebart** [comment]
Thanks! works like a charm! I was almost certain that only my n00bness to understand the code in these unittests was the core problem ;-)

**Comment by bcyang** [comment]
FWIW,

`
from jenkinsapi.jenkins import Jenkins
jargs = dict(
    baseurl='http://your.jenkins.host:8080/,
    username=os.getenv('JENKINS_USERNAME'),
    password=os.getenv('JENKINS_PASSWORD'),
)
jenkins = Jenkins(**dict(jargs, requester=CrumbRequester(**jargs)))design
`
