### ISSUE TITLE
get_queue_items_for_job throws exception upon encountering nameless task

### ISSUE THREAD

**Issue by TristenHayfield** [pycontribs/jenkinsapi#530]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION
0.2.16

##### Jenkins VERSION
2.39

##### SUMMARY

When an executor goes off-line and a build-up of items in the queue occurs, eventually
the jenkinsapi Queue method get_queue_items_for_job raises a KeyError: 'name'  exception.

Looking more closely and at the offending queue item:

```python
{'actions': [], 'buildable': True, 'buildableStartMilliseconds': 1483952411641, 'why': 'windows-build is offline', 'blocked': False, 'task': {'_class':                     
'org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask'}, 'url': 'queue/item/41706/', 'inQueueSince': 1483952411486, 'id': 41706, 'stuck':     
True, 'params': '', '_class': 'hudson.model.Queue$BuildableItem', 'pending': False} 
```
It appears that the 'task' has no name field, causing the aforementioned exception to be thrown. This was detected with an old version of jenkinsapi, but looking at the source of the new version, it appears to be just as susceptible to this problem.

you probably want to use a:
```python
if 'name' in item['task'] and item['task']['name'] == job_name:
```
in queue.py:67 

or something similar instead, if tasks can legitimately not have names.

**Comment by zzzuzik** [comment]
+1 Run in to this also..

People will start experience this problem more often with usage of Jenkins/Docker environment when slaves go up and down really fast.

**Comment by bobdoah** [comment]
> or something similar instead, if tasks can legitimately not have names.

Is it legit? I can't see any API documentation which defines whether it is or not. It seems flawed to rely on `['name'] == job_name`. I've seen unnamed tasks which _were_ associated with a Pipeline job.

**Comment by Nautigsam** [comment]
I ran into this issue in my CD environment. I got "KeyError: 'name'" quite randomly.

**Comment by VinceSJ** [comment]
Also having this issue. Items in my queue are not displaying a 'name' field inside of 'task'. Causes get_queue_items_for_job to break.

I think the proposed fix in the above commit
`if 'name' in item['task'] and item['task']['name'] == job_name:`
is **dangerous**. I know in my case it would give false positives that a given job was clear of the queue, but that would only be because of the missing name field.

**Comment by bobdoah** [comment]
> I think the proposed fix in the above commit
`if 'name' in item['task'] and item['task']['name'] == job_name:`
is dangerous.

I think your observation is correct. It also affects other methods. The `QueueItem` class expects to find a ['name'] value associated with a task. 

Where the python model falls down, if you look at the API data for a waiting workflow (pipeline) step:

    {
      "_class" : "hudson.model.Queue",
      "discoverableItems" : [
        
      ],
      "items" : [
        {
          "_class" : "hudson.model.Queue$BuildableItem",
          "actions" : [
            {
              
            }
          ],
          "blocked" : false,
          "buildable" : true,
          "id" : 12169,
          "inQueueSince" : 1509427040390,
          "params" : "",
          "stuck" : false,
          "task" : {
            "_class" : "org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask"
          },
          "url" : "queue/item/12169/",
          "why" : "Waiting for next available executor on platform-d8-1",
          "buildableStartMilliseconds" : 1509427040392,
          "pending" : false
        }
      ]
    }

is that there's no way to relate this workflow queue item to a given job.
