### ISSUE TITLE
Fix spelling of artifact (previously artefact)

### ISSUE THREAD

**Issue by jnaulty** [pycontribs/jenkinsapi#534]
Bug Report

##### Jenkinsapi VERSION
Master (v0.3.3)

##### SUMMARY
Fix spelling of artifact in documents and test function

**Comment by jnaulty** [comment]
Addressed in [PR533](https://github.com/pycontribs/jenkinsapi/pull/533)

**Comment by lechat** [comment]
"Artefact is the British spelling of the noun meaning, primarily, an object shaped by human workmanship, especially one of historical or archaeological interest. Artifact is the American spelling. Both spellings are etymologically justifiable, and both are hundreds of years old in English."

http://grammarist.com/spelling/artefact-artifact/

Really, not worth spending time.

**Comment by salimfadhley** [comment]
@lechat I'm British which is why some of the spellings are British English - I'm totally happy to adopt American English as long as we do it consistently.
