### ISSUE TITLE
Fingerprint validation fails for projects inside folders

### ISSUE THREAD

**Issue by rui-maia-alves** [pycontribs/jenkinsapi#537]
##### ISSUE TYPE
 - Bug Report

##### Jenkinsapi VERSION
jenkinsapi (0.3.3)

##### Jenkins VERSION
Jenkins ver. 2.32.2

##### SUMMARY
If you have a project inside a folder and you have fingerprint information for your artifacts, when downloading the artifacts with save_to_dir() a jenkinsapi.custom_exceptions.ArtifactBroken is received.

On function validate_for_build() the folder names are ignored when checking the job name. This is the wrong code:
if not self._data["original"] is None:
    if self._data["original"]["name"] == job:

On the second line the variable "self._data["original"]["name"]" will have the name with slashes but the job variable will have the name of the project without the folder structure.
Example:
self._data["original"]["name"] = folder1/folder2/projectA
job = projectA

##### EXPECTED RESULTS
Folder structure should be passed to the validate_for_build() function or maybe it could be ignored and the verification can check only the job name ignoring the folders

##### ACTUAL RESULTS
-

##### USEFUL INFORMATION
Possible solution (ignoring the folder names):
if not self._data["original"] is None:
    if "/" in self._data["original"]["name"]:
        jobName = self._data["original"]["name"].split("/")
        jobName = jobName[len(jobName) - 1]
    else:
        jobName = self._data["original"]["name"]
    if jobName == job:
        if self._data["original"]["number"] == build:
            return True

**Comment by lechat** [comment]
The working with folders needs to have bigger attention. As I am not using folders, I will gladly accept pull requests with fixes.
