### ISSUE TITLE
Job.is_enabled() looks for the wrong value from Jenkins

### ISSUE THREAD

**Issue by mindthump** [pycontribs/jenkinsapi#540]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION

2.29 (but visibly in 3.3)

##### Jenkins VERSION

2.19.4

##### SUMMARY

in Job.is_enabled() Jenkins (sometimes?) returns "disabled_anime" in the 'color' 

##### EXPECTED RESULTS

should return False

##### ACTUAL RESULTS

returns True, because it only looks for 'disabled' in the color

##### USEFUL INFORMATION

Workaround:

            data = self.jenkins_job.poll(tree='color')
            if 'disabled' in data.get('color', ''):
```

**Comment by lechat** [comment]
I never seen such value, must be introduced by some plugin or by recent Jenkins change. How does this look in Jenkins? What is the difference between "disabled" and "disabled_anime"?

**Comment by mindthump** [comment]
I know the "*_anime" are the names for the status ball when it's blinking -- I think this might happen when you disable a project while it's still running then check for its status. I will try this out later when I'm at work to confirm it.
