### ISSUE TITLE
File "requirements/dev-requirements.txt" missing from package

### ISSUE THREAD

**Issue by JonathanRRogers** [pycontribs/jenkinsapi#546]
##### ISSUE TYPE
 - Bug Report

##### Jenkinsapi VERSION
0.3.4

##### Jenkins VERSION
Irrelevant

##### SUMMARY
Package from pypi.python.org won't build because setup.py looks for nonexistent 'requirements/dev-requirements.txt'

##### EXPECTED RESULTS
I expected "python setup.py" to run successfully.

##### ACTUAL RESULTS
$ python setup.py
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    for line in open('requirements/dev-requirements.txt')
IOError: [Errno 2] No such file or directory: 'requirements/dev-requirements.txt'

**Comment by berdario** [comment]
Yup, I'm seeing the same issue... it's really annoying to not be able to build the package independently

**Comment by dnguyen9** [comment]
+1 agreed

**Comment by edutaluo** [comment]
i'm seeing the same bug on macOS 10.12.4

**Comment by Wooble** [comment]
The correct solution would be to add a MANIFEST.in to the project, and use the check-manifest package to make sure you're actually getting the correct files in the sdist.

**Comment by kudrom** [comment]
Is this going to be fixed some day?

**Comment by nitintt1991** [comment]
I am facing the same issue. Jenkinsapi is not getting installed.Could anyone please look into this.
Is there any other way to query build results in jenkins except via jenkinsapi as it is not even getting installed let alone querying results

**Comment by bretttolbert** [comment]
I am seeing this issue too. I have a package that depends on jenkinsapi. If I install it with setuptools (python setup.py develop) I get this error:

error: [Errno 2] No such file or directory: 'requirements/dev-requirements.txt'

As a workaround, if I run < pip install jenkinsapi > beforehand, I don't get the error.

**Comment by nitintt1991** [comment]
I tried pip install jenkisnapi but that didn't work stating the same error message:
IOError: [Errno 2] No such file or directory: 'requirements/dev-requirements.txt'. I need to install this package somehow. If anyone has faced the same issue and resolved it, please lket me know how can I get jenkisnapi. Thanks

**Comment by berdario** [comment]
@nitintt1991 you're probably using an old version of pip

This problem affects the setup.py (which prevents installing or other operations on it without checking out the whole git repository with the `dev-requirements.txt`, including regenerating the wheel file)

but installing via the wheel file doesn't require interpreting the setup.py, which thus sidesteps the issue. pip should prefer automatically the wheel file (unless it's an old version, which is why I'm suspecting it)

try

    pip install 'https://pypi.python.org/packages/bb/41/ab877c247cf9ec803b0a843fd58aab11031afb013f7066c0638a22e6e906/jenkinsapi-0.3.4-py2.py3-none-any.whl#md5=c3dc537a7f6d202db43de4f3c99432d1'

to force selecting the wheel

**Comment by nitintt1991** [comment]
@berdario Thanks!! I would try that out.

**Comment by nitintt1991** [comment]
@berdario I still got the same error:
StackTrace looks like this:
Downloading/unpacking https://pypi.python.org/packages/bb/41/ab877c247cf9ec803b0a843fd58aab11031afb013f7066c0638a22e6e906/jenkinsapi-0.3.4-py2.py3-none-any.whl
  Downloading jenkinsapi-0.3.4-py2.py3-none-any.whl (62kB): 62kB downloaded
  Running setup.py egg_info for package from https://pypi.python.org/packages/bb/41/ab877c247cf9ec803b0a843fd58aab11031afb013f7066c0638a22e6e906/jenkinsapi-0.3.4-py2.py3-none-any.whl
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-XXvrIs-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-XXvrIs-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-XXvrIs-build
Storing complete log in /home/nsomani/.pip/pip.log
:(

**Comment by berdario** [comment]
@nitintt1991 as I wrote before

> you're probably using an old version of pip

(and setuptools)

I reproduced the issue with version 1.0.2 of pip, but with version 1.5.2 (which is more than 3 years old) the wheel installation succeeds already.

Are you using a pip version more than 3 years old?

**Comment by nitintt1991** [comment]
Hey @berdario I did upgrade pip and the command worked like charm. Thanks so much

**Comment by Nasrin-Shiraly** [comment]
Hi @berdario 
I'm getting the same error:
...\appdata\local\temp\pip-build-7zgnbs\brew\setup.py", line 22, in <module>
  with open('requirements.txt') as fid:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

and my pip is update
Requirement already up-to-date: pip in c:\python27\lib\site-packages

**Comment by nitintt1991** [comment]
@Nasrin-Shiraly I have seen so many cases where we get this sort of error and it's really annoying. I personally believe you should always create a virtual environment which you can dedicate to a specific library with which you will be working, let's say I wanted to work with pandas and I created a virtual evnv(Creating it is super easy, there are so many sites that can assist you to make one) and then started working on it. You will almost never get any error while installing packages in virtual environment, trust me  and remember always avoid using sudo with pip while installing any python packages, that can make your directory vulnerable to any malicious content inside the package.
