### ISSUE TITLE
Allow specifying certificates file for self-signed certificates

### ISSUE THREAD

**Issue by klauern** [pycontribs/jenkinsapi#548]
##### ISSUE TYPE
 - Feature Idea

##### Jenkinsapi VERSION
`0.3.4`

##### Jenkins VERSION
ANY

##### SUMMARY
As it appears that you use `requests` to facilitate HTTP requests to Jenkins.  I have only used the `requests` module sparingly, but I know that I have had to use this specific feature in order to work with it:

> You can pass verify the path to a CA_BUNDLE file or directory with certificates of trusted CAs:
> 
> ```python
> >>> requests.get('https://github.com', verify='/path/to/certfile')
> ```

##### USEFUL INFORMATION

Documentation on passing custom CA file: http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

**Comment by joaompinto** [comment]
This is already available but the Jenkins class parameter uses a different name:
`J = Jenkins('https://github.com, ssl_verify='/path/to/certfile')`
