### ISSUE TITLE
Allow using multiple requesters at the same time

### ISSUE THREAD

**Issue by tuukkamustonen** [pycontribs/jenkinsapi#551]
##### ISSUE TYPE

Feature Idea

##### SUMMARY

I need to use both `KrbRequester` and `CrumbRequester` at the same time, and current implementation doesn't support that.

So, I need to create a class that combines features from both. Something else would be nice, but I don't have a suggestion on how to implement it, really. The maintainer(s) are probably already aware of this issue, and have some idea?

**Comment by lechat** [comment]
I am, maintainer, not using Kerberos and not using crumbs, so I have no place to test such requester... Please submit pull request for your combined class, we will review code and accept it.
