### ISSUE TITLE
Incorrect build status reported (after calls to is_running)

### ISSUE THREAD

**Issue by harlowja** [pycontribs/jenkinsapi#552]
##### ISSUE TYPE
 - Bug Report

##### Jenkinsapi VERSION

jenkinsapi==0.3.4

##### Jenkins VERSION

Jenkins ver. 2.53

##### SUMMARY

When I am doing the following:

```build.is_running()```

Then later

```
passed = 0
build_status = build.get_status()
if build_status in [constants.STATUS_SUCCESS,
                             constants.STATUS_PASSED]:
    passed += 1
```

The build_status doesn't seem to be using the same data ```build.is_running()``` is using and in order to make this work I have to do a `build.poll()` which seems wrong and unneeded.

##### EXPECTED RESULTS

The build status to match what `is_running()` is using.

##### ACTUAL RESULTS

The wrong status.

**Comment by lechat** [comment]
`get_status()` returns status of finished build (build's field "result"), while `is_running()` returns field "building". Both functions poll Jenkins to get latest data.

So in your case you need to get build status only when `is_running()` returns `False`.

**Comment by christensson** [comment]
I have the same issue, I found out that `self.poll()` inherited from `JenkinsBase` only sets `self._data` if argument `tree` evaluates to False. And since `self.poll()` is called from `is_running` with `tree='building'` `self._data` will never be updated.

**Comment by harlowja** [comment]
Ya, sounds about right. I just honestly gave up on this library for doing that kind of stuff (which it does all over the place...) and wrote a tiny one that just does what I want correctly.

**Comment by harlowja** [comment]
If others want that tiny library I'll get it up to https://github.com/harlowja/tinyjenkins soon.
