### ISSUE TITLE
Unable to trigger a Jenkins build remotely with file parameter using python requests

### ISSUE THREAD

**Issue by ankuagar** [pycontribs/jenkinsapi#559]
##### ISSUE TYPE
How to trigger a parameterized jenkins job remotely using python requests passing in a file parameter? 

##### Jenkinsapi VERSION

N/A

##### Jenkins VERSION
2.63

##### SUMMARY
I have a Jenkins job that accepts a file parameter. I want to trigger it remotely using python requests library.

##### EXPECTED RESULTS
I was expecting the remote job to be triggered with the contents of file.log saved in ${WORKSPACE}/files/abc.zip

##### ACTUAL RESULTS
This code triggers a build but the file /some/file/path/file.log is not posted to the Jenkins job. 
The contents are not available in ${WORKSPACE}/files/abc.zip

##### USEFUL INFORMATION
I did this

```
url = 'myurl/buildWithParameters'
data = {'Jenkins-Crumb': '8f4d0320c0982763098571789b2b65ec', 'token': 'mytoken'}
filepath='/some/file/path/file.log'
files = {'file': ('files/abc.zip', open(filepath, 'rb')) }
r = requests.post(url, data=data, files=files)
```

**Comment by lechat** [comment]
Take a look here:

https://github.com/pycontribs/jenkinsapi/blob/get_tree/jenkinsapi/job.py#L186
