### ISSUE TITLE
ImportError: No module named jenkinsapi_utils.compat

### ISSUE THREAD

**Issue by rpoojary** [pycontribs/jenkinsapi#562]
jenkinsapi-0.3.5.dev9
##### SUMMARY
Getting this error "ImportError: No module named jenkinsapi_utils.compat" When trying to import Jenkins .." from jenkinsapi.jenkins import Jenkins"

Was working fine couple of hours ago ..

**Comment by stevekuznetsov** [comment]
This is the stack-trace we see:

```
    from jenkinsapi.jenkins import Jenkins
  File "/usr/lib/python2.7/site-packages/jenkinsapi/__init__.py", line 51, in <module>
    from jenkinsapi import (
  File "/usr/lib/python2.7/site-packages/jenkinsapi/api.py", line 15, in <module>
    from jenkinsapi.jenkins import Jenkins
  File "/usr/lib/python2.7/site-packages/jenkinsapi/jenkins.py", line 12, in <module>
    from jenkinsapi.jobs import Jobs
  File "/usr/lib/python2.7/site-packages/jenkinsapi/jobs.py", line 6, in <module>
    from jenkinsapi.job import Job
  File "/usr/lib/python2.7/site-packages/jenkinsapi/job.py", line 23, in <module>
    from jenkinsapi_utils.compat import to_string
ImportError: No module named jenkinsapi_utils.compat
```

**Comment by stevekuznetsov** [comment]
@ssbarnea pretty sure the error is from c641d2a5f2c0ccaac9dca9665b01ee1460cf2378

**Comment by ssbarnea** [comment]
@stevekuznetsov Right, I will be fixing it as I already know what I missed. I will not make the 0.3.5 without it, and without making the tests stable.

**Comment by stevekuznetsov** [comment]
@ssbarnea Cool! Thanks for taking a look!

**Comment by rpoojary** [comment]
@ssbarnea thanks

**Comment by ssbarnea** [comment]
I already fixed this bug with https://github.com/pycontribs/jenkinsapi/commit/1a6b01a01f092b37fd150273b2a69789d52c10f0 on master branch, just do a pull.
