### ISSUE TITLE
add sorin account as maintainer on pypi

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/jenkinsapi#568]
@salimfadhley Please add my PYPI account (**sorin**) as maintainer of jenkinsapi package, so we can automate the release on a new version from tagged builds on Travis.

https://pypi.python.org/pypi?:action=role_form&package_name=jenkinsapi

**Comment by lechat** [comment]
I've automated release to PyPi, release 0.3.6 was done automatically.
