### ISSUE TITLE
Parameters are not sent in job invocation

### ISSUE THREAD

**Issue by alvaromunoz** [pycontribs/jenkinsapi#569]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION
0.3.4
##### Jenkins VERSION
2.60.1
##### SUMMARY

I configured a job to have a custom parameter using this: https://wiki.jenkins.io/display/JENKINS/Repository+Connector+Plugin

I can't set its value.
```
jobName="DemoJob"
build_params = {
    'version': '1.2.3',
}
jenkins = Jenkins(settings.DOFE_JENKINS_URL, requester=CrumbRequester(baseurl=settings.DOFE_JENKINS_URL, username=settings.DOFE_JENKINS_USER, password=settings.DOFE_JENKINS_TOKEN))
    job = jenkins[jobName]
    qi = job.invoke(build_params=params)

print("### JENKINS PARAMS: " + str(params))
print("### QUEUE PARAMS: " + str(qi.get_parameters()))
qi.block_until_building(delay=1)
print("### JOB PARAMS: " + str(qi.get_build().get_params()))
```
##### EXPECTED RESULTS

```
### JENKINS PARAMS: {'version': '123'}
### QUEUE PARAMS: {'version': '123'}
### JOB PARAMS: {'version': '123'}
```
##### ACTUAL RESULTS

```
### JENKINS PARAMS: {'version': '123'}
### QUEUE PARAMS: 
### JOB PARAMS: 
```
##### USEFUL INFORMATION
String parameters work OK, but not https://wiki.jenkins.io/display/JENKINS/Repository+Connector+Plugin

```

```

**Comment by lechat** [comment]
Each parameter plugin adds its own parameter class and require explicit support by jenkinsapi. We only have support for native parameter classes and for classes that people contributed to jenkins api.

You are most welcome to code support for that plugin and submit pull request for it.

**Comment by alvaromunoz** [comment]
Thank you! I'll change the parameters to String and modify my job invocations.
