### ISSUE TITLE
Installed successfully, but initialized failed

### ISSUE THREAD

**Issue by chengyuzhou** [pycontribs/jenkinsapi#580]
##### ISSUE TYPE

 - How to set the python api url with "pretty = true" argument

##### Jenkinsapi VERSION
0.3.4
##### SUMMARY
The statement "Jenkins('http://localhost:8080')"  runes with error , as the following showes:

ERROR:root:Failed request at http://localhost:8080/api/python with params: {'tree': 'jobs[name,color,url]'} jobs[name,color,url]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zhouchengyu/Documents/WorkSpace/JenkinsEvn/lib/python2.7/site-packages/jenkinsapi/jenkins.py", line 53, in __init__
    JenkinsBase.__init__(self, baseurl, poll=not lazy)
  File "/Users/zhouchengyu/Documents/WorkSpace/JenkinsEvn/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 35, in __init__
    self.poll()
  File "/Users/zhouchengyu/Documents/WorkSpace/JenkinsEvn/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 57, in poll
    data = self._poll(tree=tree)
  File "/Users/zhouchengyu/Documents/WorkSpace/JenkinsEvn/lib/python2.7/site-packages/jenkinsapi/jenkins.py", line 58, in _poll
    if not tree else tree)
  File "/Users/zhouchengyu/Documents/WorkSpace/JenkinsEvn/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 81, in get_data
    response.raise_for_status()
  File "/Users/zhouchengyu/Documents/WorkSpace/JenkinsEvn/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://localhost:8080/api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D

##### EXPECTED RESULTS
no error

##### ACTUAL RESULTS
as the above show

##### USEFUL INFORMATION
It seems the correct url should be "http://localhost:8080/api/python?pretty=true" ,but the actual url is "http://localhost:8080/api/python"

```

```

**Comment by lechat** [comment]
You need to pass your Jenkins credentials to `Jenkins('http://localhost:8080')`:

```
jenkins = Jenkins('http://localhost:8080', 'admin', 'admin123')
```
Note that password could be either password or Jenkins API token.

**Comment by lechat** [comment]
also, `pretty=true` parameter just tells Jenkins to format json output for humans and nothing else.

**Comment by chengyuzhou** [comment]
Thank you very much ,it helps a lot ,but there's still another question .

        There is one master machine and many slave machines for our jenkins environment . For safety ,I deploy jenkins environment on my own computer for testing. On my own computer , when i add username and password argument and run "jenkins = Jenkins('http://localhost:8080', 'myname', 'mypassword')" ,it runs correctly . But when i log in one slave machine by ssh and run "J = Jenkins('https://jenkins.p1staff.com/','myname','mypassword')" ,it still failes with some error. I don't know whether there are some other restrictions for https protocol . The error infomation is in the attaching file.
      By the way ,when i visiting "https://jenkins.p1staff.com/api/python" and "http://localhost:8080/api/python" in my browser ,the result seems correctly.
[error_info.txt](https://github.com/pycontribs/jenkinsapi/files/1269076/error_info.txt)

**Comment by arbabnazar** [comment]
@lechat I am getting somewhat the same error, I can connect to jenkins using your provided example:
`jenkins = Jenkins('https://jenkins.example.net', 'admin', 'xxxxxxxxxxxxxxxxxxx-api-token')`
and able to get the version and user:
```
jenkins.version
 '1.651.3'
```
But I cannot get the info about the jobs:
```
jenkins.keys()
 []
```
where should I look about it.

Thanks
