### ISSUE TITLE
create job failed when the config is byte type

### ISSUE THREAD

**Issue by flyheart** [pycontribs/jenkinsapi#582]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION
0.3.4

##### Python VERSION
Python 3.5
##### SUMMARY

when use ``Jobs.create(self, job_name, config)`` method to create a job,  if the config is byte type, it will create job failed.

##### EXPECTED RESULTS

create job success

##### ACTUAL RESULTS

create job failed

##### USEFUL INFORMATION

when use Jobs.create method to create a job, if the config is byte, it will wrap it as a string
```
    def create(self, job_name, config):
        """
        Create a job

        :param str jobname: Name of new job
        :param str config: XML configuration of new job
        :returns Job: new Job object
        """
        if job_name in self:
            return self[job_name]

        if config is None or len(config) == 0:
            raise JenkinsAPIException('Job XML config cannot be empty')

        params = {'name': job_name}
        # the below code is the problem occure
        config = str(config)  # cast unicode in case of Python 2
```
if the config is a byte, the ``config=str(config)`` will make a wrong xml format, 
e.g. 
```
config = b'123'
assert config==b'123'
config = str(config) 
assert config=="b'123'" #   the config will become "b'123'", which changed the config's content 
```

**Comment by lechat** [comment]
Jenkinsapi just passes payload to Jenkins REST API. If Jenkins decides not to check if payload is not expected XML, then jenkinsapi won't do that for jenkins either. Perhaps your code need to check what is being passed to `create`.

**Comment by flyheart** [comment]
Maybe I  describe wrong. What I mean is if I pass a right xml format config to ``create`` method, but the config is a byte, then the create method's ``config=str(config)`` will make the config to a wrong method. But if I pass a string type config to ``create`` method, it use ``requests.post`` method to create Jenkins job. In ``requests.post`` method, if the playload is string, it will use  encoding is ``ios-8859-1`` to make it to bytes and can not changed.  If there's Chinese character in the config, it will encounter an error encode.
Summary: what I hope the ``create`` method do is if config is a byte, ***do not convert it to string***.
Thanks for your replying.
