### ISSUE TITLE
Unable to Access SSL enabled Jenkins API when working behind the proxy

### ISSUE THREAD

**Issue by ashutoshjha1** [pycontribs/jenkinsapi#585]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY
Unsable to Access Jenkins API when , Jenkins is running behind SSL enabled Nginx and APIs are being access from a machine which is behind proxy.
##### EXPECTED RESULTS

It should have worked
##### ACTUAL RESULTS

It throws error
##### USEFUL INFORMATION

```
![l_212c tmp](https://user-images.githubusercontent.com/14108679/30859352-efe9933a-a2e0-11e7-9e85-2b4a6cfc3b01.PNG)


```

**Comment by ynyrllw** [comment]
you will need to add your proxy environment settings to python to work, the os python library would be handy here. specifically os.environ. e.g.  os.environ['http_proxy']

**Comment by lechat** [comment]
This has nothing to do with jenkinsapi.
