### ISSUE TITLE
We shouldn't have to fetch all the nodes to get a single node. This can make getting a single node very slow.

### ISSUE THREAD

**Issue by geraldini** [pycontribs/jenkinsapi#615]
https://github.com/pycontribs/jenkinsapi/blob/369dc54a8d5bb1f4e985c647378b9e1e62c26961/jenkinsapi/jenkins.py#L255

**Comment by lechat** [comment]
After this change single `Node` object is going to be created. Still all nodes will be read by `Nodes`, I need to add tree parameter to Nodes.poll to read only node names and urls.
