### ISSUE TITLE
Connection Error on get_job(jobname) when used for remote jenkins server

### ISSUE THREAD

**Issue by dharmjit** [pycontribs/jenkinsapi#618]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION
0.3.6
##### Jenkins VERSION
2.32.2
##### SUMMARY

Connection Error on get_job method. 
I am using below code to get job details.
```
def get_server_instance():
    jenkins_url = 'http://XX.XX.XX.XX:8080'
    server = Jenkins(jenkins_url, username = 'xxxx', password = 'xxxxx')
    return server

	
	
"""Get job details of each job that is running on the Jenkins instance"""
def get_job_details():
    server = get_server_instance()
    for j in server.get_jobs():
        job_instance = server.get_job(j[0])
        print('Job Name:'+(job_instance.name))
        print('Job Description:'+job_instance.get_description())
        print('Is Job running:'+job_instance.is_running())
        print('Is Job enabled:'+job_instance.is_enabled())
```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8080)
##### EXPECTED RESULTS

should be able to get job details
##### USEFUL INFORMATION

```

```

**Comment by lechat** [comment]
Please give full stack trace.

**Comment by dharmjit** [comment]
Closing this issue as it is resolved after configuring URL in jenkins server
