### ISSUE TITLE
How do you limit the number of builds to include in response for 'get_jobs()'?

### ISSUE THREAD

**Issue by dwstyner** [pycontribs/jenkinsapi#630]
##### ISSUE TYPE
 - How to specify the builds to return from get_jobs() or get_jobs_info()

##### Jenkinsapi VERSION
0.3.6

##### Jenkins VERSION
2.86.4+

##### SUMMARY
Calling get_jobs() returns all builds instead of last 50 as documented.

##### EXPECTED RESULTS
I would like to be able to specify allBuilds, noBuilds lastBuild, etc. 

##### ACTUAL RESULTS
For jobs with a very large number of builds saved, the query will time out and fail.

##### USEFUL INFORMATION
Code defaults to tree='allBuilds[number,url]'

import jenkinsapi
from jenkinsapi import Jenkins

J = Jenkins(<url>, <userid>, <apiToken>)   #even tried 'timeout=3600'
for j, jobj in J.get_jobs():
<will time out on jobs with sufficiently large number of builds saved>
```

**Comment by gsingers** [comment]
It would also be helpful to be able to search for jobs.  get_jobs is super slow if you have a lot of jobs/builds.
