### ISSUE TITLE
Is there any method in the library to retrieve jobs from specific folder

### ISSUE THREAD

**Issue by apaandiyan** [pycontribs/jenkinsapi#636]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - How to...

##### USEFUL INFORMATION

```

```

**Comment by lechat** [comment]
There is no such method, but I will accept pull request for this.

**Comment by andrewgy8** [comment]
@apaandiyan Can you give a specific use case of what exactly you want this method to do? What do you envision it returning?
