### ISSUE TITLE
Is it possible to get last build parameter for a build parameter as default value

### ISSUE THREAD

**Issue by madhusaragadam** [pycontribs/jenkinsapi#637]
##### ISSUE TYPE

 - How to set last build parameter value as default value for current builds parameter

##### SUMMARY
I wanted to create a jenkins build parameter for which i wanted to set the last build parameter value as default one.

**Comment by lechat** [comment]
You mean that you're looking for ready made code to use in your project? This library provides the means to do what you want and issues are to report bugs and ask for new features, and not to ask for help on writing code for your use case.
