### ISSUE TITLE
how to update a job

### ISSUE THREAD

**Issue by felixglow** [pycontribs/jenkinsapi#638]
##### ISSUE TYPE
 - How to...

##### SUMMARY
how to update a job config, i can't find the function, can someone help me?

**Comment by lechat** [comment]
```
my_job = Jenkins("http://localhost:8080")["my_job"]
config = my_job.get_config()
# do something with config
my_job.update_config(config)
```

https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi/job.py#L567

**Comment by felixglow** [comment]
thank you very much!

**Comment by felixglow** [comment]
@lechat thank you very much!

**Comment by HeartIsBeat** [comment]
I use update_config throw an error.
`xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1`
![image](https://user-images.githubusercontent.com/20472976/76603944-d0999c00-6548-11ea-845a-4a650e87af08.png)

code is like this:
```
j = Jenkins(JENKINS_URL, username=JENKINS_USER, password=JENKINS_PASSWORD)
    import xml.etree.cElementTree as ET
    config = j[job_name].get_config()
    root = ET.fromstring(config.strip())
    builders = root.find('builders')
    command = builders.find('hudson.tasks.Shell').find('command')
    command.text = "ls"
    new_config = ET.tostring(root, encoding="UTF-8")
    print(new_config)
    j[job_name].update_config(new_config)
```
