### ISSUE TITLE
How to build with multi-parameters via build_job(self, jobname, params=None)

### ISSUE THREAD

**Issue by F35X70** [pycontribs/jenkinsapi#639]
##### ISSUE TYPE

 - How to...

##### Jenkinsapi VERSION
jenkinsapi (0.3.6)

##### Jenkins VERSION
Jenkins ver. 1.580.1

##### SUMMARY

call build_job/invoke with multi parameters .e.g
[{'name': 'JENKINS_LIST', 'value': '11111 22222'}, {'name': 'JENKINS_AP', 'value': 'ap'}, {'name': 'JENKINS_MODULE', 'value': 'ikl'}, {'name': 'JENKINS_PUT', 'value': False}, {'name': 'JENKINS__FILES', 'value': ''}, {'name': 'JENKINS_BRA', 'value': 'xxx_dev'}, {'name': 'JENKINS_BUILD', 'value': 'userdebug'}]   

##### EXPECTED RESULTS

invoke recevice all {'name':n,'value':v}

##### USEFUL INFORMATION

```

```

**Comment by lechat** [comment]
`job.invoke` takes `build_params` dict, not list. Dict should look like this:

```python
{
    'JENKINS_LIST': '1111 2222',
    'JENKINS_AP': 'ap',
....
}
```

**Comment by F35X70** [comment]
Hi lechat:
   thank for your reply
