### ISSUE TITLE
How actively maintained is this project?

### ISSUE THREAD

**Issue by andrewgy8** [pycontribs/jenkinsapi#647]
##### ISSUE TYPE
 - Maintenance Activity

##### SUMMARY

First off, I really enjoy this projects goals and concept. So thanks for all the work! 

Given it has a large following and a number of issues/features that could use addressing, I feel like this project could use some TLC. Mainly, improving **test coverage** (so that way we can make large strides in closing out some of the issues quickly), improving/updating the **documentation**, making it easier to clone and **develop with minimal setup effort**, and closing some of the **outstanding PRs**. 

I would like to make some decent PRs, but I want to be assured that they will be reviewed and eventually merged (if applicable) at some point.  Is there anyone here that could help (or can I help in some way) in reviewing and closing some the PR's? 

Pardon me if this is not the place to discuss this, but I have tried contacting the maintainers through email, Google Groups, the Gitter channel and Github. 

Thanks for any clarification!

**Comment by lechat** [comment]
I am the only maintainer left, and I am watching for PRs/issues daily. I tend to accept PRs with good features and code quite quickly, but sometimes real life stands in a way.

Most of the outstanding PRs are not accepted because submitters have no interest of fixing errors, so they left behind.

**Comment by andrewgy8** [comment]
Hmm, thats a shame.  Perhaps I'll have some time coming up to clean up any ones that seem worthy of keeping.  Any ones in particular we could use? 

Also, do you have any idea what the roadmap/future ideas would be for this project? I'd like to contribute in the most efficient way possible. I don't mind writing more tests to describe and lock down current functionality, and basically hitting the points I mentioned above.

**Comment by andrewgy8** [comment]
Or better yet, is there a channel which I can ask further questions that are not directly related to issues?

**Comment by lechat** [comment]
My email in in README.rst :)

**Comment by ssbarnea** [comment]
I am reopening it let other know that if they want to maintaint it, there is still room for additional maintainers.

**Comment by andrewgy8** [comment]
If you need someone to review and such Ill be able to help with that, but I don’t know if I’ll be  able to submit large features, etc.  I must warn that I just picked up maintainership of another large project so my time will be split. Let me know if you guys need help and I’ll try my best.

**Comment by ssbarnea** [comment]
@andrewgy8 I added you to the repository so you could review, merge. If you need pypi release, ping me and I will do it. Later i will automate release when tag is pushed, already did this on other projects.

**Comment by lechat** [comment]
Wait, would it be good to ask me as well? Not that I am against that, but out of common courtesy?

The tag automation is already there, so nothing needs to be added.

**Comment by ssbarnea** [comment]
@lechat Oops, my mistake. I hope you can take care of it and assure it lives on ;)
