### ISSUE TITLE
comparison between jenkinsapi and python-jenkins libraries

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/jenkinsapi#649]
We need to make a comparison of multiple jenkins libraries and guide users about which one they should use or avoid. If possible we should also aim to consolidate these libraries, if possible, so efforts will no longer be divergent. It is much better to have one library that is well mantained than many less maintained ones.

* https://pypi.org/project/python-jenkins/ - under OpenStack umbrella, well maintained, @ssbarnea is one of the maintainers
* https://pypi.org/project/jenkinsapi/ - less maintained, also @lechat being one active maintainer
* https://pypi.org/project/jenkins/ - abandonware - we may be able to obtain the pypi namespace in the future if we want, see https://github.com/lgastako/jenkins/issues/3

**Comment by lechat** [comment]
Firstly, I am maintainer of https://pypi.org/project/jenkinsapi/  and not @ssbarnea.

Secondly, I am fine with maintaining this library and not fine with contributing to OpenStack due to various reasons.

It is much better have different libraries that one and only one. I let users choose what works for them.

**Comment by ssbarnea** [comment]
@lechat I corrected the description. Now the important questions to answer would be about differences in api and functionality.

Your remark about OpenStack made me a bit curious but we can take if offline. One thing that I know for sure about OpenStack projects is that you cannot really do anything alone, as any change would require peer review, usually two. This makes merges much slower and one year ago the jenkins library was in pretty bad shape due to lack of interest. This changed and now there are at least 3-4 active contributors. 

Another aspect about python-jenkins is that while is still under openstack, is no longer an openstack project which gives it some extra flexibility. We had discussions about moving the issue tracker from  storyboard to github or launchpad as both are easier to use but no decision was made yet. 

One thing that I remarked about jenkinsapi is that CI is currently broken but this may have to so with the recent migration from travis.org to travis.com, not sure. One think where I jenkinsapi has an extra bonus is that it does run the tests with two versions of jenkins stable and latest, which is something really useful.

**Comment by lechat** [comment]
Last time I've checked OpenStack required signing some agreement and then it relied on gerrit, which is overkill for my humble self. Some time ago I had time and will to learn how to deal with gerrit, but that time is in the past.

CI is broken due to some changes in credential plugin. I will take a look into that once I will get some free time.

**Comment by ssbarnea** [comment]
@lechat CLA signing take less than a minute, no paperwork involved. Regarding gerrit, remember what I say: I started using Gerrit less than two years ago so with github I have a much longer experience. Once you get it, you will find the PR process pretty bad and time consuming. To make a CR on gerrit you just need to do run "git review", same command will update an existing review if it was already raised. (`pip install git-review` first).

If the bad credentials are the one from pypi, I cannot help there as I am not listed as maintainer. For the other pypi projects I automated the publishing using the "pycontribs" account. Only thing needed to make a new release is to push a new tag on github, which is already limited. Ping me if you need need, I am always on irc as I need it for my day to day work.

**Comment by lechat** [comment]
The CI build is broken because of changes in Jenkins, which has nothing to do with pypi. The tag based release is working for about a year or so.

Let's agree to disagree on OpenStack.

**Comment by cpratik025** [comment]
Hi @lechat ,
I am looking up for some help with getting a jenkins-python api script created to count the no of builds that are done over a day. If you can help me with that would be much appriciated.
Thanks
