### ISSUE TITLE
Jenkins pipelines API returns changesets instead of changeset

### ISSUE THREAD

**Issue by bbgobie** [pycontribs/jenkinsapi#651]
##### ISSUE TYPE
 - Bug Report
##### Jenkinsapi VERSION
0.3.6 but eyeballing the code it is currently still an issue
##### Jenkins VERSION
2.107.3
##### SUMMARY
Jenkins pipeline jobs no longer return a result for "changeset" it has become "changesets"
No idea why, couldn't find documentation on the change.

##### EXPECTED RESULTS
being able to call Build.get_changeset_items()

##### ACTUAL RESULTS
  File "/usr/lib/python3.6/site-packages/jenkinsapi/build.py", line 136, in get_changeset_items
    if 'items' in self._data['changeSet']:

##### USEFUL INFORMATION
Create a standard manual Jenkins job, and view the API
I get a changeset section like below

```
 "changeSet" : {
    "_class" : "hudson.plugins.git.GitChangeSetList",
    "items" : [
      {
        "_class" : "hudson.plugins.git.GitChangeSet",
        "affectedPaths" :  ....

```
With a pipeline job, the API returns "changeSets" instead of "changeSet"

```
  "changeSets" : [
    {
      "_class" : "hudson.plugins.git.GitChangeSetList",
      "items" : [
        {
          "_class" : "hudson.plugins.git.GitChangeSet",
          "affectedPaths" : [ ...
```

**Comment by bbgobie** [comment]
https://github.com/pycontribs/jenkinsapi/pull/654

Sorry, I'm not a python expert, I wasn't able to run your nosetests, tried with a few different versions of Python, but they all gave me basically like 200+ errors
I think all the test files that don't have a class defined in them fail?

**Comment by rgarrigue** [comment]
Same version same issue againt pipeline job with sources from SVN. Tried bbgobie patch, didn't worked out for me. Tried s/changeSet/changeSets in build.py, didn't worked out either. Here is my original error stack.

```
Traceback (most recent call last):
  File "flemme.py", line 32, in <module>
    cli()
  File "C:\Python37\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python37\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Python37\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python37\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "flemme.py", line 26, in lgb
    return lgb.get_revision()
  File "C:\Python37\lib\site-packages\jenkinsapi\build.py", line 84, in get_revision
    vcs = self._data["changeSet"]["kind"] or "git"
KeyError: 'changeSet'

```

**Comment by bbgobie** [comment]
Sorry, my if statement was very bad. Can't remember what I was doing before I committed.

I don't think your SVN changeset is related to my poor change.  Will have to try and setup a svn scm and look more closely.

**Comment by lechat** [comment]
This was fixed and merged to master.
