### ISSUE TITLE
226 failed tests

### ISSUE THREAD

**Issue by dineshdh** [pycontribs/jenkinsapi#660]
##### ISSUE TYPE

 - How to...

##### SUMMARY

`nosetests -v jenkinsapi_tests` is returning
```
Ran 270 tests in 20.414s

FAILED (errors=226)
```

##### EXPECTED RESULTS

All tests passing

##### ACTUAL RESULTS

`FAILED (errors=226)`

##### USEFUL INFORMATION

How are we meant to do development on the api ???

```

```

**Comment by lechat** [comment]
We don't use `nose`, but use `pytest`. Also all testing is encapsulated within `tox`. 

If you need to test library, please install `tox` and use it.
