### ISSUE TITLE
couldn't connect to new installed jenkins with user admin with Security Realm set to " Delegate to servlet container"

### ISSUE THREAD

**Issue by walthhy** [pycontribs/jenkinsapi#676]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION
jenkinsapi-0.3.6
##### Jenkins VERSION
Jenkins ver. 2.153, chart stable/jenins 0.22.0
##### SUMMARY
couldn't connect to jenkins using jekninsapi with default usr "admin". But we can access it from browser with "admin". 
If through browser, i changed security Realm to Jenkins’ own user database and create a new user, then jenkinsapi works as expect with new created user

##### EXPECTED RESULTS
jenkinsapi could work with default user "admin" with Security Realm set to " Delegate to servlet container"

##### ACTUAL RESULTS
>>> from jenkinsapi.jenkins import Jenkins
>>> J = Jenkins(' http://cctf-jenkins.default.svc:8080', username='admin', password='admin')
ERROR:root:Failed request at http://cctf-jenkins.default.svc:8080/jenkins/api/python with params: {'tree': 'jobs[name,color,url]'} jobs[name,color,url]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/src/app/env/lib/python2.7/site-packages/jenkinsapi/jenkins.py", line 59, in __init__
    JenkinsBase.__init__(self, baseurl, poll=not lazy)
  File "/usr/src/app/env/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 35, in __init__
    self.poll()
  File "/usr/src/app/env/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 57, in poll
    data = self._poll(tree=tree)
  File "/usr/src/app/env/lib/python2.7/site-packages/jenkinsapi/jenkins.py", line 64, in _poll
    if not tree else tree)
  File "/usr/src/app/env/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 81, in get_data
    response.raise_for_status()
  File "/usr/src/app/env/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Server Error for url: http://cctf-jenkins.default.svc:8080/jenkins/api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D

```
xxx
```

**Comment by lechat** [comment]
Is that full exception message?

**Comment by lechat** [comment]
If this is full exception and no Jenkins stacktrace, then there is no connection to Jenkins was made. Please check if you are accessing Jenkins via proxy in your browser.

**Comment by JonasVerhofste** [comment]
I can confirm that the new release breaks _something_. Code that worked perfectly fine on release 0.3.6 breaks on 0.3.7 (I think it has something to do with the crumb requester, but I'm not sure yet, haven't had the time to test yet).

**Comment by lechat** [comment]
The integration tests do test CrumbsRequester in freshly installed Jenkins. I haven't seen any failures. Would be interesting to get failing test case.

**Comment by JonasVerhofste** [comment]
I'll try to reproduce the error when I have the time. Do the tests enable csrf-protection withing Jenkins?

**Comment by lechat** [comment]
There is a test that enables it to test CrumbsRequester.
