### ISSUE TITLE
get_downstream_jobs() does not differentiate between jobs with the same name

### ISSUE THREAD

**Issue by jwlarocque** [pycontribs/jenkinsapi#678]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY
In jenkinsapi/job.py, line 585:  
`<job>.get_downstream_jobs()` sometimes returns the wrong job when there is another job with the same name but not downstream.  

For example, with this structure:   
- Create Mobile Test Jobs
  - Login Test
- Create Desktop Test Jobs
  - Login Test

```
server = Jenkins(URL, username=USER, password=TOKEN)
for job in server["Create Desktop Test Jobs"].get_downstream_jobs():
    print job.url
```

##### EXPECTED RESULTS
```
<server url>/job/Desktop/job/Login
```

##### ACTUAL RESULTS
```
<server url>/job/Mobile/job/Login
```

**Comment by lechat** [comment]
I assume that structure above is made using Folders plugin and there is no full support for that plugin in this library. I am open for contributions.
