### ISSUE TITLE
build_job failed with an error:jenkins.JenkinsException: <exception str() failed>

### ISSUE THREAD

**Issue by tm2018** [pycontribs/jenkinsapi#681]
what i want to know is how to build job with my branch!
##### Jenkins VERSION
2.111
##### SUMMARY

 I try to build job by jenkins-api,but it failed when i add my branch in my code 

but it failed and it can build sucess when i remove build_params

PS:
the branch is controled by gitlab

##### EXPECTED RESULTS

what i expect is that i can build_job with my own branch by jenkins api

##### ACTUAL RESULTS

get error like this:

Traceback (most recent call last):
  File "E:/all_gits/call_jenkins/test.py", line 16, in <module>
    print server.build_job(build_job_name,build_params)
  File "D:\Python27\lib\site-packages\jenkins\__init__.py", line 1278, in build_job
    'POST', self.build_job_url(name, parameters, token)))
  File "D:\Python27\lib\site-packages\jenkins\__init__.py", line 594, in jenkins_request
    raise JenkinsException(msg)
jenkins.JenkinsException: <exception str() failed>
##### USEFUL INFORMATION

```
jenkins_server_url = "http://ip:8080/jenkins/"
username = 'xxx'
password = 'yyy'

def connect_jenkins(url, username, password):
    server = jenkins.Jenkins(url, username=username, password=password)
    user = server.get_whoami()
    return server
build_params = {'branch': 'origin/master'}
server = connect_jenkins(jenkins_server_url,username,password)
server.build_job(build_job_name,build_params)
```

**Comment by lechat** [comment]
Firstly, I am not sure why library files were converted to huge `jenkins_init.py` files. Perhaps this is Windows specific mangling, but it makes stack trace useless.
Secondly, I can't find find none of `raise JenkinsException` or `jenkins_request`. That leads me to thinking that you are using old version. 

Which version do you use? Use `pip freeze` to find out.

**Comment by tm2018** [comment]
yeah! my version of jenkins api is python-jenkins==1.4.0...

i install it by pip install jenkins, and my python is 2.7.15. whether i need to update my jenkins or python ?

**Comment by lechat** [comment]
Sorry, this repository and issues are about library is called "jenkinsapi" and not "python-jenkins". Please raise your issue in another repository.
