### ISSUE TITLE
Latest master isn't released on pypi

### ISSUE THREAD

**Issue by tom-dalton-fanduel** [pycontribs/jenkinsapi#691]
##### ISSUE TYPE

 - How to use the code merged in #685?

The code merged into master by #685 on 20th Jan doesn't seem to be in the latest published build. Is there a release schedule for this feature and if not could we get a new release containing this feature?

##### SUMMARY

I'm running into auth issues using a jenkins with a github backend and it looks like it's related to rate-limiting on the auth side of things. Hopefully #685 will fix my issue but I can't use it yet as it's not published.

**Comment by austinbutler** [comment]
Should be possible to install from Github with `pip3 install git+git://github.com/pycontribs/jenkinsapi.git` or similarly in `setup.py`.

**Comment by lechat** [comment]
I released v0.3.9
