### ISSUE TITLE
allBuilds is too expensive to happen on instantiation

### ISSUE THREAD

**Issue by jamesmeador** [pycontribs/jenkinsapi#696]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION
0.3.8

##### Jenkins VERSION
2.150.2

##### SUMMARY
In our environment, these two lines can time out for jobs with long retention:

```
jenkins = Jenkins(jenkins_url, requester=requester)
job = jenkins.get_job(job_name)
```

##### EXPECTED RESULTS
I don't expect the instantiation of a job to hit the `allBuilds` tree.

##### ACTUAL RESULTS
`jenkins.get_job(job_name)` times out after 10 seconds attempting to list thousands of builds. The issue is noticeably worse when the master is under load.

**Comment by jamesmeador** [comment]
It's worth noting that the jenkins documentation says this, emphasis mine:

> Retrieving all builds
To prevent Jenkins from having to load all builds from disk when someone accesses the job API, the builds tree only contains the 50 newest builds. If you really need to get all builds, access the allBuilds tree, e.g. by fetching …/api/xml?tree=allBuilds[…]. **Note that this may result in significant performance degradation if you have a lot of builds in this job**.

**Comment by lechat** [comment]
Actually documentation is wrong: the API returns 100 latest builds. :)

I will submit PR where `Job` will check if `Jenkins` was created with option `lazy` set to True and will not load all jobs in that case.

**Comment by jamesmeador** [comment]
The PR certainly sounds helpful. Although the documentation seems accurate, because when I visit:

`job_name/api/python?tree=allBuilds%5Bnumber%2Curl%5D`

I get 776 results (or however many are in retention).

**Comment by lechat** [comment]
`allBuilds` will return all builds. `builds` will return 100 builds, not 50 as stated in docs.

**Comment by jamesmeador** [comment]
Oh. But I don't see `builds` anywhere in this code path. Did I miss something?

**Comment by jamesmeador** [comment]
(Although I do agree they should update their docs!) The documentation quote was simply to point out the performance issues with the `allBuilds` query.
