### ISSUE TITLE
set and delete Credentials.CredentialsById should be done by id also

### ISSUE THREAD

**Issue by hummerstudio** [pycontribs/jenkinsapi#708]
now they are done by description:
def __setitem__(self, description, credential)
def __delitem__(self, description)

but description is not unique, however credential_id is.

Am I right？If I am right, I can write the code,but we need to talk about how do we deal with the previous code.

**Comment by lechat** [comment]
The code was written when credential_id was not exposed by Jenkins API, so the only way to find credential was by description.

I would suggest changing parameter name `description` to `description_or_id` and then handle it assuming that it may contain either id or description.

**Comment by hummerstudio** [comment]
@lechat I found `__setitem__(self, description, credential) `and `__delitem__(self, description)` are in `class Credentials(JenkinsBase)` in fact. `Credentials.CredentialsById` only has` __getitem__(self, credential_id)`. May I add new method `__setitem__(self, credential_id, credential)` and `__delitem__(self, credential_id)` in `class CredentialsById(Credentials2x)` to fix this?

**Comment by lechat** [comment]
No, it will not work. You can't add second pair of magic functions to the same class.

**Comment by hummerstudio** [comment]
@lechat I don't know much about the theory of magic functions. But I see CredentialsById has its own magic function __getitem__, why can't has another two magic functions?Thanks to answer.

**Comment by lechat** [comment]
Here is the guide if you are interested: https://rszalski.github.io/magicmethods/

My point is that you can have as many magic methods as you like, but I don't think that they will work.
