### ISSUE TITLE
Hangs on `running build_ext` (nixpkgs)

### ISSUE THREAD

**Issue by drets** [pycontribs/jenkinsapi#723]
Hi,

I packed your awesome project into `nixpkgs` some time ago and with the latest versions I can't make it to build: https://github.com/NixOS/nixpkgs/pull/66937

Maybe, you guys have a clue what may be the reason to hang on `running build_ext` while building?

Thanks in advance :smirk:

**Comment by lechat** [comment]
Hi

Sorry I missed this issue somehow. There is no `build_ext` function in jenkinsapi.

What do I need to run to see this issue?
