### ISSUE TITLE
Crumbs functionality is broken against > LTS 2.176

### ISSUE THREAD

**Issue by zzzuzik** [pycontribs/jenkinsapi#724]
CSRF was tighten up:
https://jenkins.io/doc/upgrade-guide/2.176/

see as well:
https://github.com/ansible/ansible/issues/61672

**Comment by wy-z** [comment]
You need https://github.com/pycontribs/jenkinsapi/blob/76d64d166d2c7c66e8cf87578d4f3113ca1bc1c0/jenkinsapi/jenkins.py#L652

**Comment by zzzuzik** [comment]
@wy-z thanks, but this doesn’t work with HTTPS

**Comment by zzzuzik** [comment]
verified; the issue is resolved in the 0.3.10 release. thank you @lechat
