### ISSUE TITLE
Is the library thread-safe?

### ISSUE THREAD

**Issue by DChrome** [pycontribs/jenkinsapi#726]
##### ISSUE TYPE
help wanted

##### SUMMARY
Is the library thread-safe? Can the `jenkinsapi.jenkins.Jenkins` instance be shared between threads or should each thread create its own instance? Can the non-blocking job invocation, queue inspection, etc. be done safely using multiple Python threads if a shared `Jenkins` object is used?

**Comment by micxer** [comment]
I would say no, because I ran into issues using it in a threaded scenario.
