### ISSUE TITLE
Cannot add credentials

### ISSUE THREAD

**Issue by piyushpriyam** [pycontribs/jenkinsapi#729]
Got response [403] in post_and_confirm_status

while

credJson = {
        'description' : description,
        'username' : username,
        'password' : password,
        'credential_id':credential_id,
        'typeName': typeName
    }

    server.credentials.__setitem__(description,server.credentials._make_credential(credJson))

Please also provide an working example.

**Comment by lechat** [comment]
Examples are here: https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi_tests/systests/test_credentials.py

**Comment by piyushpriyam** [comment]
Thanks man,
I used crumb, it solve the issue
