### ISSUE TITLE
job.invoke() cannot handle baseurl including standard port 443 / 80

### ISSUE THREAD

**Issue by linkeal** [pycontribs/jenkinsapi#732]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When adding a standard port to the baseurl for job invocations, the verification within the invoke function does not work, because in the HTTP response location the standard port is abandoned.

##### EXPECTED RESULTS
Job invokation happens succesfully.

##### ACTUAL RESULTS
Resolution of the jenkins queue is not successfull.

##### USEFUL INFORMATION

Example Code:
```
from jenkinsapi.jenkins import Jenkins
from jenkinsapi.job import Job
from jenkinsapi.utils.crumb_requester import CrumbRequester

def trigger_jenkins_job(jenkins_obj, job_url, job_name, build_parameters):
    job = Job(url=job_url, name=job_name, jenkins_obj=jenkins_obj)
    qi = job.invoke(block=True, build_params=build_parameters,cause="Triggered externally via script")
    build = qi.get_build()
    return build

def get_server_instance(jenkins_url, user, password):
    crumb_requester = CrumbRequester(baseurl=jenkins_url, username=user, password=password, ssl_verify=False)
    server = Jenkins(jenkins_url, username=user, password=password, requester=crumb_requester, ssl_verify=False, lazy=True)
    return server

def test_invoke_job():
    jenkins_url = "https://jenkins-company.com:443"
    user = "myuser"
    password = "mypassword"
    jenkins_obj = get_server_instance(jenkins_url, user=user, password=password)

    build_parameters = {"SRC_PATH":"/tmp/test1",
                        "DEST_DIR":"/tmp/test2"}

    trigger_jenkins_job(jenkins_obj=jenkins_obj,
                        job_url=jenkins_url + "/job/copy_file/",
                        job_name="copy_file",
                        build_parameters=build_parameters)
```

```
Traceback (most recent call last):
  File "/usr/local/bin/mapr_volumes", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mapr_volumes/cli.py", line 121, in main
    build_parameters=build_parameters)
  File "/usr/local/lib/python3.7/site-packages/mapr_volumes/jenkins.py", line 23, in trigger_jenkins_job
    qi = job.invoke(block=True, build_params=build_parameters,cause="Triggered externally via script")
  File "/usr/local/lib/python3.7/site-packages/jenkinsapi/job.py", line 234, in invoke
    raise ValueError("Not a Queue URL: %s" % redirect_url)
ValueError: Not a Queue URL: https://jenkins-company.com.net/queue/item/96516/
```

**Comment by lechat** [comment]
It looks to me that your Jenkins is configured to have url `https://jenkins-company.com.net` and for some reason you prefer calling it `https://jenkins-company.com:443`. Why not either change Jenkins url in Jenkins config or just use url that is configured in Jenkins?

**Comment by linkeal** [comment]
Thank you for the quick response @lechat, appreciate you being active as a main contributor here.
Indeed and this is currently my workaround to set the baseurl to https://jenkins-company.com.net. 

I guess then it was just a design decision of this package here that the baseurl always needs to fit with the url configured in Jenkins?

Another error that I faced before that is somehow related:
- baseurl is a tunnel address because jenkins is not directly reachable due to firewalls (e.g. localhost:1234)
- Jenkins however has a proper url configured (e.g. https://jenkins-company.com:443)
- during job invoke we will follow the http location redirection and thus cannot reach Jenkins anymore (because of firewalls)

However the PR would not fix this. I think this would be a bigger restructure so that you always use the base_url and path and not the redirect url anymore.

**Comment by lechat** [comment]
I don't see a point of having standard https port to be present in url. 

I think that it is best to follow [Jenkins docs for reverce proxy](https://wiki.jenkins.io/display/JENKINS/Jenkins+behind+an+NGinX+reverse+proxy) rather than changing `jenkinsapi` for your specific and unusual case.

**Comment by linkeal** [comment]
Alright. Thanks anyway.
