### ISSUE TITLE
Support for user specified delay (quiet period) when starting a job

### ISSUE THREAD

**Issue by skorhone** [pycontribs/jenkinsapi#743]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
jenkinsapi does not support passing delay parameter (quiet period) when starting job

##### EXPECTED RESULTS
jenkinsapi allows user to define quiet period for job's invoke method

##### ACTUAL RESULTS
jenkinsapi does not allow user to define quiet period for job's invoke method. This causes a notable delay (default 5secs) for user that is invoking the task

##### USEFUL INFORMATION
delay parameter can be passed to jenkins in uri using format: delay=XXsec . e.g. delay=0sec

**Comment by daniel1608** [comment]
+1 for this feature

**Comment by kkpattern** [comment]
We also want this feature badly. We actually want using this feature to set a longer delay.

**Comment by kkpattern** [comment]
I created a pull request #758 for this.
