### ISSUE TITLE
Building a job results in "ValueError: Not a Queue URL", but job gets built anyway

### ISSUE THREAD

**Issue by loximann** [pycontribs/jenkinsapi#754]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When building a job with Jenkins.build_job(), the queue URL validity check always fails, because the port is included in my Jenkins URL. The job is anyway built.

##### EXPECTED RESULTS
The job is built and the script finishes cleanly.

##### ACTUAL RESULTS
The job is built, but the script end with "ValueError: Not a Queue URL"

##### USEFUL INFORMATION

In my case, the validity checker in Job.invoke fails, because it tries to check that redirect_url:
`http://<JENKINS_SERVER>/queue/item/893/`
starts with
`http://<JENKINS_SERVER>:8080/queue/item`

Removing the port from the Jenkins server address fixes the issue, but I guess this is not the desired behaviour.

I am not sure how to check for the URL validity in all cases, otherwise I would try to submit a PR...

Stack trace:
```[...]
  File ".../.local/lib/python3.7/site-packages/jenkinsapi/job.py", line 236, in invoke
    raise ValueError("Not a Queue URL: %s" % redirect_url)
ValueError: Not a Queue URL: http://<JENKINS_SERVER>/queue/item/893/
```

**Comment by lechat** [comment]
It is another case of misconfigured Jenkins. You need to set proper Jenkins address in Jenkins settings.

**Comment by loximann** [comment]
1. Could you tell me how is Jenkins misconfigured?
2. How about the second part of my bug report, that the job is run despite the error being sent?

**Comment by lechat** [comment]
Your Jenkins is listening on port 80, while Jenkins URL in settings is set to port 8080. All works fine till when you request something, but breaks when Jenkins starts returning configured url in replies.

**Comment by loximann** [comment]
Just to be clear: the URL in the reply does not include any port. Therefore, if I don't include any port in the address when I create the Jenkins instance, all is good.

Any comments about point 2? In other words, if the job was successfully queued, how come it is not a valid queue URL?
