### ISSUE TITLE
useCrumb => use_crumb

### ISSUE THREAD

**Issue by frankcash** [pycontribs/jenkinsapi#755]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION

Master

##### SUMMARY

Camel casing is more in line with other parameter variables in the function i.e. `ssl_verify`.  

It is also more common in python to snake case than to camelcase.
##### USEFUL INFORMATION

https://www.python.org/dev/peps/pep-0008/

https://github.com/pycontribs/jenkinsapi/search?q=useCrumb&unscoped_q=useCrumb

**Comment by lechat** [comment]
I will gladly accept PR for this.

**Comment by frankcash** [comment]
@lechat perfect, I've created a PR for it
