### ISSUE TITLE
jenkinsapi don't support parameterized  build in pipeline as code?

### ISSUE THREAD

**Issue by rajeshpp** [pycontribs/jenkinsapi#764]
Hi Team,

Does jenkinsapi support parameterized build in Jenkinsfile (pipeline as code)?

Here is my pipeline as code (Jenkinsfile):
================================================
''''''''''
pipeline {
    agent { label 'NODE1' }
  stages {
    stage ('Provider') {
      steps {
  script {
   def name
   def userInput = input(
    id: 'userInput', message: 'testing params',
                parameters: [
     string(defaultValue: 'Rajesh',
                           description: 'Enter The Name you want.',
                           name: 'name')
    ]
   )
   env.name = userInput.name?:'Rajesh'
  }
  sh "echo ${name}"
   }
    }
  }
}
''''''''''
I am trying to build this job by supplying parameters as:
''''''''''''''''
>>> from jenkinsapi.jenkins import Jenkins
>>> J = Jenkins(JENKINS_URL,username,XXXXXXXXXX',ssl_verify=False)
>>> J.build_job('PythonTrigger',{'name':'Rajesh'})
''''''''''''''''
And the error, I am getting is:
''''''''''''''''''''''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/jenkinsapi/jenkins.py", line 203, in build_job
    self[jobname].invoke(build_params=params or {})
  File "/usr/local/lib/python3.6/site-packages/jenkinsapi/job.py", line 179, in invoke
    raise BadParams("This job does not support parameters")
jenkinsapi.custom_exceptions.BadParams: This job does not support parameters

'''''''''''''''''''''''
Please help in this issue.

**Comment by lechat** [comment]
Userinput is not a parameter to a job. It is a special step in build that will ask user for input. How would you imagine to support that?

If you have an idea, I am happy to accept pull request.

**Comment by rajeshpp** [comment]
> Userinput is not a parameter to a job. It is a special step in build that will ask user for input. How would you imagine to support that?
> 
> If you have an idea, I am happy to accept pull request.

But, userInput is part of Jenkins and it works when build is triggered. why can't jenkinsapi supply those params? Or After build triggered, sleep until parameter invoking part arrive and supply those params with the help of a python code. why can't we do that? is it impossible or difficult?

**Comment by lechat** [comment]
Jenkinsapi works with Jenkins REST API (to some extent). There is no REST API to call for UserInput. Surely, it can be done, but it is not easy. You will be better off creating actual parameters for your job instead of relying on Userinput.

**Comment by rajeshpp** [comment]
> Jenkinsapi works with Jenkins REST API (to some extent). There is no REST API to call for UserInput. Surely, it can be done, but it is not easy. You will be better off creating actual parameters for your job instead of relying on Userinput.

It will be awesome, if it is done. I wonder, why this was not implemented in Jenkins REST API. If possible, please try to develop it.

**Comment by rajeshpp** [comment]
Do we have any plan of implementing the idea that I mentioned above?

**Comment by lechat** [comment]
I don't. Because parametrized builds are already supported and automating user input is hacky. 

Also, nobody else wants this feature - nobody commented on it.
