### ISSUE TITLE
Project internal: Add CI pipeline

### ISSUE THREAD

**Issue by sodul** [pycontribs/jenkinsapi#804]
Something that would be useful for the project would be to have a CI pipeline built into it.

GitHub Actions are a good option because they are built into GitHub and free for open source projects.

This mean that PRs could be automatically checked with a linter and the 

For static code analysis, SonarCloud is a free option and it can run independently if code coverage reports are not required.
This is the analysis on my fork: https://sonarcloud.io/dashboard?id=sodul_jenkinsapi

**Comment by lechat** [comment]
This project has CI pipeline for many years. Though is not based on Github actions or sonarcloud.

**Comment by sodul** [comment]
Ah my bad ... the TravisCI tests are failing though. Is there an effort to bring them back to stability so contributors can have a strong confidence of success on PRs?
