### ISSUE TITLE
Proposal: drop support for python 2.7

### ISSUE THREAD

**Issue by sodul** [pycontribs/jenkinsapi#805]
Python 2 was officially EOL in 2020. Many of the supporting tools and libraries are becoming incompatible with python 2.7.

Keeping backward compatibility makes development more cumbersome for new contributors.

Pip:
```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
```

The current CI pipeline for the project are all failing, for both python 2 and python 3. I believe they would be much easier to keep working without the need to support python 2.

**Comment by lechat** [comment]
I removed testing for 2.7 and will not look into backwards compatibility from now on.
