### ISSUE TITLE
a problem with old jenkins

### ISSUE THREAD

**Issue by gittor** [pycontribs/jenkinsapi#808]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY
```
jenkins_url = "http://10.10.12.29:8080"
server = Jenkins(jenkins_url, username="********", password="********")
print server.get_jobs()
```
when I run the code, JenkinsBase.get_data() returns jobs with url `http://localhost:8080`.like
```
"jobs": [{
        "_class": "hudson.model.FreeStyleProject",
        "name": "xxx",
        "url": "http://localhost:8080/job/xxxx/",
        "color": "aborted"
    }, {
        "_class": "hudson.model.FreeStyleProject",
        "name": "yyyy",
        "url": "http://localhost:8080/job/yyyy/",
        "color": "blue"
    }
}
```
but the 10.10.12.29 is not my ip, then Jenkins.py raises an exception.

**Comment by joelee2012** [comment]
@gittor  maybe you want to try https://api4jenkins.readthedocs.io/en/latest/user/example.html#credential

**Comment by gjabouley-invn** [comment]
Hello, it could be a Jenkins misconfiguration.
What is configured for "Manage Jenkins-> Configure System -> Jenkins URL"? It should be set explicitly to `http://10.10.12.29:8080`

**Comment by gittor** [comment]
> Hello, it could be a Jenkins misconfiguration.
> What is configured for "Manage Jenkins-> Configure System -> Jenkins URL"? It should be set explicitly to `http://10.10.12.29:8080`

Thank you. Now I'm curious about why jenkins behaves like this. Why it doesn't read the computer's ip

**Comment by gjabouley-invn** [comment]
Jenkins cannot know its own url, assuming you can host it:
- as simple ip:port
- using an http proxy front-end (nginx, apache)
- using a domain
- ...

Best practice is to set the url to access Jenkins in this field. It is then used to generate urls in email for example, and also in http headers.

**Comment by gittor** [comment]
Thank you all
