### ISSUE TITLE
Is this library still actively maintained?

### ISSUE THREAD

**Issue by gjabouley-invn** [pycontribs/jenkinsapi#811]
Hello

First thanks for all you work, it makes our live way easier 👍 

we are relying on this library for our automation. So far it works fine.

Still we are getting concerned that it seems unmaintained anymore:
* no new release since 1.5 year
* Travis CI broken so hard to submit new changes
* Several ongoing PRs

Can you recommend another alternative, ideally which expose a similar API and that is actively maintained.

**Comment by joelee2012** [comment]
you may want to try https://api4jenkins.readthedocs.io/en/latest/ as alternative

**Comment by gjabouley-invn** [comment]
Hi
thanks, i've seen your other comments regarding your lib ;)
It is already added as a candidate in our list, but for now seems too young and without yet a community to support it.
But very nice job, we will anyway try-test it

**Comment by lechat** [comment]
I just released new version 0.3.12 with some fixes.
