### ISSUE TITLE
What is the most stable version for jenkinsapi

### ISSUE THREAD

**Issue by VAIBHAVCES** [pycontribs/jenkinsapi#826]
##### ISSUE TYPE

 - Bug Report
 -  0.3.11 jenkinsapi version giving me 

##### SUMMARY

When I am using jenkinsapi:0.3.11 and calling the following methods:
```
job = jenkins.get_job(jobName)
```
this is creating the problem in finding the job with error message
```
  File "/usr/lib/python3.7/site-packages/jenkinsapi/jenkins.py", line 156, in get_job
    return self.jobs[jobname]
  File "/usr/lib/python3.7/site-packages/jenkinsapi/jobs.py", line 89, in __getitem__
    raise UnknownJob(job_name)
jenkinsapi.custom_exceptions.UnknownJob: 'jobname'
```
I have this very old thread discussing the same problem and in that it was suggested to use 0.3.9
https://github.com/pycontribs/jenkinsapi/issues/770 

And on using this version it is working fine for me 
Can we debug what is the root cause for this problem and also do we have any CHANGELOG.md file something where we can easily track the stable recommended latest version to use 

##### EXPECTED RESULTS
Maintaining a changelog.md file 

##### USEFUL INFORMATION

```
  File "/usr/lib/python3.7/site-packages/jenkinsapi/jenkins.py", line 156, in get_job
    return self.jobs[jobname]
  File "/usr/lib/python3.7/site-packages/jenkinsapi/jobs.py", line 89, in __getitem__
    raise UnknownJob(job_name)
jenkinsapi.custom_exceptions.UnknownJob: 'jobname'

```

**Comment by lechat** [comment]
This is caused by folders in your Jenkins, `jenkinsapi` has no support of them and nobody seems to make a PR to get it working.
