### ISSUE TITLE
Method "get_nodes" in init gets wrong name for master node

### ISSUE THREAD

**Issue by xBudii** [pycontribs/jenkinsapi#827]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In the __init__ file when get_nodes() is being called, the resulting list of nodes contains a false 
master node name, in my case it was "Built-In Node" as the return call accesses "displayName" 
from the returned request call. 

##### EXPECTED RESULTS
[{'name': 'master', 'offline': False}, ...]

##### ACTUAL RESULTS
[{'name': 'Built-In Node', 'offline': False}, ...]

##### USEFUL INFORMATION
I think the issue is related to the change that occured when Jenkins gets updated to a newer version. 
(Please correct me if i am wrong)

Workaround (for me, dont know if it works for everyone):
In get_nodes i changed the line: 
`return [{'name': c["displayName"], 'offline': c["offline"]}`
to
`return [{'name': c["assignedLabels"][0]["name"] if c["assignedLabels"][0]["name"] == "master" else c["displayName"], 'offline': c["offline"]}`

**Comment by lechat** [comment]
This is now fixed in release 0.3.12
